src/components/common/Alert.tsx
src/components/common/ConfirmAlert.tsx
src/components/writepage/ProjectWritePageFooter.tsx
src/pages/ProjectWritePage.tsx

확인 창과 확인 취소 창을 만들기 위한 작업
- 확인 창 UI 작업
- 확인 닫기 창 UI 작업 ( 현재 임시 디자인 사용중)

[feat] Alert UI 구현

---

.eslintrc
src/pages/ProjectDetailPage.tsx

Fixes #17 
파이어베이스 데이터 가져오기 로직 추가 및 데이터 조회 테스트
- 파이어베이스에 목데이터 추가
- 파이어베이스 getDoc로직 추가
- 데이터 뿌리기 로직  테스트
- @baesee0806 팀원찾기 페이지에서 상세페이지로 넘어갈 때 파라미터는 docId로 넘겨주세요
(알고계시겠지만 확인차 전달드립니당)

[PR] 파이어베이스 데이터 가져오기 로직 추가

---

src/components/login/LoginModal.tsx
src/utils/modal.ts

로그인/회원가입 모달창이 열려 있을 때, body 스크롤을 방지하는 기능을 개선했습니다.
* 기존 : 스크롤이 사라지면서 페이지가 16px만큼 움직임.
* 개선 : 스크롤이 사라지지 않아 페이지 움직임이 없음.
* utils/modal.ts 파일 내에 `preventScroll`, `allowScroll` 함수 추가
* `LoginModal` 컴포넌트 마운트/언마운트 시 함수 적용
.

[feat] 로그인/회원가입 모달창 UI - 스크롤 방지 기능 개선

---

src/apis/boardService.ts
src/components/common/ConfirmAlert.tsx
src/components/common/LabelInput.tsx
src/components/common/SkillButton.tsx
src/components/writepage/ProjectWritePageBody.tsx
src/components/writepage/ProjectWritePageFooter.tsx
src/components/writepage/ProjectWritePageHeader.tsx
src/components/writepage/WritePagePosition.tsx
src/components/writepage/WritePageStack.tsx
src/hooks/useWrite.ts
src/pages/ProjectWritePage.tsx

게시글 작성시 받아올 데이터 form 작업과 파이어 베이스 DB에 넣어주는 글 작성 로직 및 Date 포맷 전부 밀리초로 통일 및 Position 데이터를 오브젝트 형태로 변경
- Form Value hook 작성
- Firebase Create Project 로직 추가
- Firebase 글 작성 로직시 밀리초 포맷으로 변경

[게시글 작성] 게시글 작성

---

src/components/common/Alert.tsx
src/components/common/ConfirmAlert.tsx
src/components/editpage/EditPagePosition.tsx
src/components/editpage/EditPageStack.tsx
src/components/editpage/ProjectEditPageBody.tsx
src/components/editpage/ProjectEditPageFooter.tsx
src/components/editpage/ProjectEditPageHeader.tsx
src/components/writepage/WritePagePosition.tsx
src/hooks/index.ts
src/hooks/useWrite.ts
src/pages/ProjectEditPage.tsx
src/pages/ProjectWritePage.tsx

글 수정 UI 작업과 Feedback: Alert창과 Confirm Alert창이 보일시 스크롤 막기와  FormValue naming 변경
- 글 수정 UI 작업
- Alert, confirmAlert 스크롤 막기
- Form Value naming 변경 및 적용

[글 수정] 글 수정 UI 작업 및 피드백 적용

---

src/apis/mypageUsers.ts
src/components/Header.tsx
src/components/common/ProjectItem.tsx
src/components/common/ProjectList.tsx
src/components/common/SkillButton.tsx
src/components/mypage/CareerRadioInput.tsx
src/components/mypage/Careers.tsx
src/components/mypage/CheckboxButton.tsx
src/components/mypage/MyPageInfo.tsx
src/components/mypage/MyPageProfileImage.tsx
src/components/mypage/PositionCheckBox.tsx
src/components/mypage/SkillList.tsx
src/pages/MyPage.tsx
src/pages/PublicProfilePage.tsx
src/react-app-env.d.ts
src/utils/positions.ts

로그인 기능 진행 전 더미데이터로 유저 정보를 가져오는 작업을 진행했습니다.
* 임시 컴포넌트인 프로젝트 아이템 누락된 키(key) 추가
* 다른 페이지에서의 헤더 색상 버그 수정
* 마이페이지 유저 정보 조회 추가
* 프로필 이미지 없을 경우 처리
.

[feat] 마이페이지 유저 정보 조회 추가

---

src/components/common/ConfirmAlert.tsx
src/components/common/LabelInput.tsx
src/components/writepage/ProjectWritePageHeader.tsx
src/hooks/useWrite.ts
src/pages/ProjectEditPage.tsx
src/pages/ProjectWritePage.tsx
src/utils/validation.ts

프로젝트 게시판 작성시 규칙에 맞게 작성하기 위하여 Validation 추가 및 Figma대로 confirm alert 디자인 수정
- Validation 추가 및 적용
- confirm alert 디자인 수정

[feat] 프로젝트 게시판 작성 Validation

---

src/apis/mypageUsers.ts
src/components/mypage/CareerRadioInput.tsx
src/components/mypage/Careers.tsx
src/components/mypage/MyPageInfo.tsx
src/components/mypage/MyPageProfileImage.tsx
src/hooks/useProfileImage.ts
src/pages/MyPage.tsx

Closes #48 
마이페이지 프로필 이미지 수정, 삭제기능 추가 작업 진행했습니다.
- 프로필 이미지 수정하기 추가
- 프로필 이미지 삭제하기 추가
- 프로필 이미지 관련 함수 커스텀 훅으로 분리
(수정 후 DB 업데이트 되는 부분은 닉네임 및 여러 정보 수정 작업 때 같이 진행할 계획입니다.)
.

[feat] 마이페이지 프로필 이미지 수정, 삭제 기능 추가

---

src/components/ModalContainer.tsx
src/components/login/LoginModal.tsx
src/components/popup/NoteModal.tsx

스크롤이 되지 않는 에러를 수정했습니다.
- ModalContainer의 useEffect를 제거했습니다.
.

[fix] 스크롤 에러 수정

---

package.json
src/apis/boardService.ts
src/apis/imageService.ts
src/components/TextEditor.tsx
src/components/common/Alert.tsx
src/components/common/ConfirmAlert.tsx
src/components/editpage/EditPagePosition.tsx
src/components/editpage/EditPageStack.tsx
src/components/editpage/ProjectEditPageBody.tsx
src/components/editpage/ProjectEditPageFooter.tsx
src/components/editpage/ProjectEditPageHeader.tsx
src/components/projectDetail/TitleThumbnailArea.tsx
src/components/writepage/ProjectWritePageBody.tsx
src/components/writepage/ProjectWritePageFooter.tsx
src/components/writepage/WritePagePosition.tsx
src/hooks/index.ts
src/hooks/useEditBoard.ts
src/hooks/useWrite.ts
src/pages/ProjectEditPage.tsx
src/pages/ProjectWritePage.tsx
src/types/write/writeType.ts
src/utils/validation.ts

글 수정 작업시 필요한 Data를 불러오고 기존 데이터 유지 하면서 수정 기능작업
- 수정 버튼 클릭시 원본 게시글 데이터 불러오기
- 수정 전 데이터 default value 값 지정하기
- 썸네일 UI 추가
- 썸네일 업로드 및 수정 기능 추가
- 소스맵 오류 pakage.json 에서 소스맵 false 처리
- Validation 버그 수정
- 수정 or 작성 버튼 클릭시 z-index로 인한 클릭 오류 수정
- 수정 기능 완성

[feat] 글 수정 & 삭제 & 썸네일 기능 및 그 외 기능 추가

---

src/apis/boardService.ts
src/apis/imageService.ts
src/components/editpage/ProjectEditPageBody.tsx
src/components/findproject/FindProjectHeader.tsx
src/components/findproject/FindProjectList.tsx
src/components/writepage/ProjectWritePageBody.tsx
src/hooks/useEditBoard.ts
src/hooks/useWrite.ts
src/pages/FindProjectPage.tsx
src/pages/ProjectEditPage.tsx
src/pages/ProjectWritePage.tsx

팀원찾기 페이지 UI 작업완료
- 팀원찾기 페이지 UI 작업
- Tabmenu 카테고리 이벤트 처리 & CSS 처리
- Toggle Button 이벤트 처리 & CSS 처리
- 썸네일 이름 오타 수정

[feat] 팀원찾기 페이지 UI 작업완료

---

src/components/common/ApplyPositionButton.tsx
src/components/projectDetail/ApplicantListArea.tsx
src/components/projectDetail/ApplyButtonArea.tsx
src/components/projectDetail/ApplyModal.tsx
src/components/projectDetail/InviteModal.tsx
src/pages/ProjectDetailPage.tsx

Fixes #58 
- 팀원 초대 모달
- 지원하기 모달
- Alert 컴포넌트 연결

[PR] 지원하기, 초대하기 버튼 모달 UI 구현

---

src/apis/getPost.ts
src/apis/mypageUsers.ts
src/components/common/SkillButton.tsx
src/components/findproject/FindProjectHeader.tsx
src/components/mypage/CareerRadioInput.tsx
src/components/mypage/Careers.tsx
src/components/mypage/CheckboxButton.tsx
src/components/mypage/MyPageInfo.tsx
src/components/mypage/MyPageProfileImage.tsx
src/components/mypage/NicknameInput.tsx
src/components/mypage/PositionCheckBox.tsx
src/components/mypage/SkillList.tsx
src/hooks/index.ts
src/hooks/useProfileImage.ts
src/hooks/useUpdateProfile.ts
src/types/mypage/userInfo.ts
src/utils/positions.ts
src/utils/validation.ts

Closes #54 
마이페이지 유저 정보 수정 후 DB 갱신 작업을 진행중입니다.
* 닉네임 유효성 검사 추가 
* 마이페이지 유저 기본 정보 상태 저장, 파이어 베이스 갱신 ((기술스택은 진행중))
* 수정 컨펌 모달창 추가
! 로컬 스토리지에서 uid 얻어오는 부분은 아직 수정 안 되었습니다.
.

[feat] 마이페이지 유저 정보 수정 추가

---

src/components/common/SkillButton.tsx
src/components/findproject/FindProjectHeader.tsx
src/components/writepage/ProjectWritePageHeader.tsx

버튼의 Transition hover 효과와 Input의 타입을 text로 변경해서 테두리 색 변경
- Skill Button Transtion 0.3s로 변경
- Toggle Button Transition 0.3s로 변경
- Write Page Input tag type text로 변경

[feat] CSS 수정

---

src/hooks/useSocialLogin.ts

회원가입 시 Firebase 사용자 컬렉션 초기화하는 기능을 추가했습니다.
회원 가입이 완료되면
- user 컬렉션에 사용자 문서 추가
- myprojects 컬렉션에 사용자 문서 추가
- outbox, inbox, notifications 컬렉션에 사용자 문서 추가
.

[feat] 회원가입 시 Firebase 사용자 컬렉션 초기화

---

src/components/common/SkillButton.tsx
src/components/editpage/EditPageStack.tsx
src/components/editpage/ProjectEditPageBody.tsx
src/components/writepage/ProjectWritePageBody.tsx
src/components/writepage/WritePageStack.tsx
src/hooks/useEditBoard.ts
src/hooks/useWrite.ts
src/pages/ProjectEditPage.tsx
src/pages/ProjectWritePage.tsx

여러 컴포넌트에서 사용하는 스킬버튼이 일부 컴포넌트에서 렌더링 문제로 값 변경이 안되서 State로 로직 변경
- 스킬버튼 로직 변경
- 스킬버튼 Type props 추가

[feat] 스킬버튼 기존 Array -> State 값으로 로직 변경

---

src/hooks/index.ts
src/hooks/useAuth.ts

useAuth 커스텀훅을 추가했습니다.
- useAuth 커스텀훅 추가
- 로컬스토리지에 저장된 유저 정보를 반환
.

[feat] useAuth 커스텀훅 추가

---

src/hooks/useAuth.ts

useAuth 커스텀훅의 반환 타입을 수정했습니다.
- 반환 타입에서 Undefined 제거
.

[fix] useAuth 반환 타입 수정

---

src/assets/styles/globalStyled.ts
src/components/mypage/CareerRadioInput.tsx
src/components/mypage/CheckboxButton.tsx
src/components/mypage/LeftTab.tsx
src/components/mypage/MyPageInfo.tsx
src/components/mypage/MyPageProfileImage.tsx
src/components/mypage/TextInput.tsx
src/pages/MyPage.tsx

Closes #84 
디자인 수정에 따라 마이페이지 UI를 변경했습니다.
* 마이페이지 탭 UI로 변경 (배경을 전체적으로 적용하기 위해 GlobalStyled 에도 100% 속성 추가)
* 프로필 이미지 UI 수정 (프로필 이미지 변경 모달창은 추가 작업 예정입니다.)
* 연락처 UI 추가 (관련 로직은 추가 작업 예정입니다.)
.

[fix] 마이페이지 UI 변경

---

src/components/mypage/LeftTab.tsx
src/components/mypage/MyPageProfileImage.tsx
src/pages/MyPage.tsx

Closes #84 
모니터 해상도가 큰 경우 마이페이지 배경 색상이 잘리는 부분과 기타 CSS를 수정했습니다.
* 마이페이지 컨텐츠 영역에 WebContainer 적용
* 배경 min,max-height 추가
* 프로필 수정버튼 z-index 조정
.

[fix] 마이페이지 UI 수정

---

src/apis/boardService.ts
src/components/ContentCard.tsx
src/components/editpage/EditPageStack.tsx
src/components/findproject/FindProjectHeader.tsx
src/components/findproject/FindProjectList.tsx
src/components/main/recommendation/MainRecommendation.tsx
src/components/writepage/WritePageStack.tsx
src/hooks/index.ts
src/hooks/useFindProject.ts
src/hooks/useWrite.ts
src/pages/FindProjectPage.tsx
src/types/write/writeType.ts
src/utils/validation.ts

프로젝트 찾기 페이지 Content Card UI 수정과 토글 버튼 필터 기능 과 카테고리 필터 기능 및 등등
- Content Card UI 수정 및 데이터 동적으로 받아오기
- 모집중 Toggle Button 필터 기능
- 카테고리 필터 기능
- 새글 작성시 uid 값 추가 및 isRecruiting 기본 값 true로 변경
- WritePage, EditPage 스타일 컴포넌트 중복 간소화
- EditType 파일안에 id, thumbnail 타입 추가
- 비지니스 로직 hooks 파일로 분리
- 글 작성 validation 수정
- Main Page Content Card 적용

[feat] 프로젝트 찾기 UI 변경 및 토글 버튼 과 카테고리 필터 기능

---

src/components/common/ModalNavigator.tsx
src/components/login/SetPositions.tsx
src/components/login/SetProfile.tsx
src/components/login/SetSkills.tsx
src/components/login/SocialLogin.tsx
src/components/popup/NoteBox.tsx
src/components/popup/NoteModal.tsx
src/components/popup/NotificationBox.tsx

쪽지 모달창 네비게이터를 추가했습니다.
- 쪽지 읽기 창 닫기버튼 추가
- 답장하기 창 닫기버튼 추가
.

[feat] 쪽지 모달창 네비게이터 추가

---

src/components/common/ConfirmAlert.tsx
src/components/mypage/MyPageInfo.tsx
src/components/mypage/MyPageProfileImage.tsx
src/components/mypage/ProfileImageModal.tsx

Closes #92 
마이페이지 프로필 수정 모달 추가 작업을 했습니다.
* Confirm 공용모달 이용하여 모달창 추가 (z-index 수정)
* 기존 프로필 수정 기능 연동
* 유저 정보 setState 위치 수정
.

[feat] 프로필 수정 모달 추가

---

src/components/login/SetPositions.tsx
src/components/login/SetProfile.tsx

- 회원가입 경력 선택 기능을 추가했습니다.
- 프로필 사진 변경 버튼을 수정했습니다.
- 회원가입 경력 선택 (1년 미만/1년 이상) 추가
- 프로필 사진 변경 모달창으로 수정
.

[feat] 회원가입 경력 선택 추가, 프로필 사진 변경 버튼 수정

---

src/components/main/Calendar/MainCalendar.tsx
src/components/main/Calendar/ProjectCalendar.tsx
src/components/main/Calendar/ProjectDetail.tsx
src/components/main/Calendar/ProjectList.tsx
src/components/main/findUsers/MainFindUsers.tsx
src/components/main/recommendation/MainRecommendation.tsx

- 메인페이지 (관심,조회)tap, (기획,디자인,프론트,백엔드)tap 기능 구현하였습니다.
- 불필요한 코드 삭제 
- 메인 페이지 tap 기능 구현
- 코드 정리

[feat] 메인 페이지 Tap 기능 

---

src/apis/mypageUsers.ts
src/components/common/ConfirmAlert.tsx
src/components/login/SetProfile.tsx
src/components/mypage/Careers.tsx
src/components/mypage/MyPageInfo.tsx
src/components/mypage/MyPageProfileImage.tsx
src/components/mypage/PositionCheckBox.tsx
src/components/mypage/SkillList.tsx
src/components/mypage/TextInput.tsx
src/hooks/useUpdateProfile.ts
src/pages/MyPage.tsx
src/react-app-env.d.ts
src/types/mypage/userInfo.ts
src/utils/validation.ts

Closes #104 
마이페이지에 추가된 연락처 변경 시 DB 반영 작업을 했습니다.
* alertConfirm창 버튼 텍스트 굵기 수정
* 마이페이지 uid 받아오는 부분에 useAuth 훅 적용
* UserInfo 타입 분리 및 email 타입 추가
* 연락처 유효성 검사 추가 (이메일 유효성 검사로 추가)
* 기존 닉네임 수정 핸들러 함수를 인풋 수정 핸들러 함수로 확장, 관련 코드들 수정
* 사용하지 않는 코드 정리
.

[feat] 마이페이지 연락처 변경 추가

---

src/apis/boardService.ts
src/components/common/ValidationToastPopup.tsx
src/components/findproject/FindProjectList.tsx
src/hooks/index.ts
src/hooks/useEditBoard.ts
src/hooks/useFindProject.ts
src/hooks/useToastPopup.ts
src/hooks/useWrite.ts
src/pages/FindProjectPage.tsx
src/pages/ProjectEditPage.tsx
src/pages/ProjectWritePage.tsx
src/types/write/writeType.ts
src/utils/validation.ts

- 글 작성 & 수정 유효성 검사를 하기 위해서
- 글 작성 & 수정 유효하지 않은 규격일 경우 Toast Popup 띄우기 위해서
- 그 외 수정사항 적용
- 글 작성 유효성 검사 추가
- 글 수정 유효성 검사 추가
- 유효성 검사 Toast Popup UI 작업 및 적용
- Toast Popup 재사용성을 고려 Custom hooks 파일로 분리
- 글 작성시 데이터에 applicants 빈 객체 추가 생성
- 오늘 날짜 받아오기 로직 추가
- 그 외 변수 타입 적용

[feat] 글 작성 & 수정 유효성 검사와 Toast Popup 생성

---

src/apis/findWithCollectionName.ts
src/apis/postDetail.ts
src/components/projectDetail/Likes.tsx
src/components/projectDetail/MemberInfoArea.tsx
src/components/projectDetail/Share.tsx
src/components/projectDetail/Views.tsx
src/components/projectDetail/WriterToShareArea.tsx
src/components/projectDetail/modals/ApplyModal.tsx
src/pages/ProjectDetailPage.tsx

Fixes #105 
`해당 이슈사항을 해결하기 위해 어떤 작업을 할 것인지 남겨주세요.`
- 좋아요 로직 오류 수정
- 조회수 기능 구현
- 상세보기 페이지 applicants 데이터 없을 시 오류 발생 부분 수정
- api 분리

[PR] 조회수 기능 구현, 좋아요 기능 로직 수정, 상세보기 페이지 오류 수정

---

src/apis/boardService.ts
src/apis/userService.ts
src/components/ContentCard.tsx
src/components/findproject/FindProjectList.tsx
src/components/main/Calendar/ProjectCalendar.tsx
src/components/main/recommendation/MainRecommendation.tsx
src/hooks/useFindProject.ts
src/pages/FindProjectPage.tsx

- 관심있는 프로젝트에 하트에 색상을 넣어 처리
- 캘린더 무한 렌더링 수정
- 글 작성시 마이 프로젝트 DB에 프로젝트 ID 생성
- Firebase myprojects 컬렉션에서 likedproject만 불러오기 처리
- 게시글 생성시 글 작성 doc.id를 myprojects 컬렉션 postedProjects에 값 넣음 처리
- 캘린더 컴포넌트에 useEffect를 한개 더 생성해 디펜던시를 분기 처리해 무한 렌더링 해결
- 팀원찾기 & 메인페이지 Content Card에 내가 관심있는 프로젝트일시 하트 색상처리

[팀원 찾기] 내가 관심 있는 프로젝트만 아이콘 색상처리 및 이 외 처리

---

src/components/popup/SendNote.tsx

쪽지 보내기 receiverUid 에러를 수정했습니다.
- useNote 훅의 parameter를 senderUid로 변경
.

[fix] 쪽지 보내기 receiverUid 에러 수정

---

src/components/popup/SendNote.tsx
src/hooks/index.ts
src/hooks/useNote.ts
src/hooks/useNotification.ts

useNote, useNotification 커스텀훅 로직을 개선했습니다.
- parameter 제거
- handleSend 함수에서 uid와 내용을 전달
.

[feat] useNote, useNotification 커스텀훅 개선

---

src/apis/postDetail.ts
src/components/main/Calendar/ProjectDetail.tsx
src/components/projectDetail/ApplicantListArea.tsx
src/components/projectDetail/ApplyButtonArea.tsx
src/components/projectDetail/Likes.tsx
src/components/projectDetail/MemberInfoArea.tsx
src/components/projectDetail/ProjectInfoArea.tsx
src/components/projectDetail/TitleThumbnailArea.tsx
src/components/projectDetail/modals/ApplyModal.tsx
src/components/projectDetail/modals/InviteModal.tsx
src/hooks/useModal.ts
src/pages/ProjectDetailPage.tsx

Fixes #121 
- 현재 참여 중인 인원에서 포지션 중복 렌더링 되는 오류 -> if state 수정으로 해결
- 초대 완료 시 화면에 바로 렌더링 안되는 오류 -> invalidateQueries로 해결
- 프로젝트 지원 시 이미 지원한 인원이 재지원 할 수 있는 오류
- 모집 완료의 경우에도 비작성자는 간단 지원하기가 가능한 오류
- 모집 완료의 경우에도 작성자가 지원자를 초대할 수 있는 오류 -> 지원자 목록 보이지 않도록 하기
- 지원 취소 기능 추가
- 현재 참여중인 인원의 프로필 사진에 마우스 오버 시 닉네임 보여주기

[PR] 프로젝트 상세보기 전반적인 로직 수정

---

src/components/common/ValidationToastPopup.tsx
src/components/login/SetPositions.tsx
src/components/login/SetProfile.tsx
src/components/login/SetSkills.tsx
src/components/popup/SendNote.tsx
src/hooks/useNotification.ts

쪽지, 알림 유효성 검사를 구현했습니다.
- 쪽지 보내기 제목, 내용 유효성 검사
- 회원가입 포지션, 경력 유효성 검사
- 회원가입 기술 스택 유효성 검사
- 회원가입 닉네임 유효성 검사
- sendNotification 알림보내기 유효성 검사
.

[feat] 쪽지, 알림 유효성검사

---

src/components/editpage/ProjectEditPageBody.tsx
src/components/editpage/ProjectEditPageFooter.tsx
src/components/projectDetail/TitleThumbnailArea.tsx
src/components/writepage/ProjectWritePageBody.tsx
src/components/writepage/ProjectWritePageFooter.tsx
src/hooks/useEditBoard.ts
src/hooks/useWrite.ts
src/utils/validation.ts

- 글 작성 & 수정 페이지 Input, Button, Text 사이즈 조정 및 색상 조정
- 글 작성 & 수정시 useMutate 로직 작성
- 디테일 페이지 썸네일 이미지 사이즈 조절
- 글 작성 & 수정 페이지 Input 사이즈 Figma에 맞게 조정
- 글 작성 & 수정 페이지 Button 색상 보라색으로 수정
- 글 작성 & 수정 페이지 Button 안에 Text Figma에 맞게 폰트 사이즈 조절
- 글 작성 & 수정시 useMutate로 invalidateQueries 처리 및 navigate 본인이 작성한 글로 이동하게 수정
- 디테일 페이지 썸네일 사진 Object-fit으로 수정

[fix] 자잘한 버그와 피드백 수정  

---

src/components/mypage/LeftTab.tsx
src/hooks/useHeader.ts
src/pages/MyPage.tsx

Closes #125 
회원 탈퇴 기능을 추가했습니다.
* 회원 탈퇴 기능 추가 (탈퇴 시 users 컬렉션에서 해당 유저의 문서가 삭제됩니다.)
* 탈퇴 시 모달창 추가
.

[feat] 회원 탈퇴 기능 추가

---

src/components/ContentCard.tsx
src/components/common/myProjectList/ProjectItem.tsx
src/components/mypage/ProjectsTab.tsx
src/components/projectDetail/MemberInfoArea.tsx
src/components/publicProfile/UserPositions.tsx
src/components/publicProfile/UserStacks.tsx
src/hooks/useProjectList.ts
src/pages/MyPage.tsx
src/pages/ProjectDetailPage.tsx
src/pages/PublicProfilePage.tsx
src/utils/positions.ts
src/utils/skills.ts

Closes #131 
공개프로필 조회, 프로젝트 리스트 기능을 작업했습니다.
* 공개프로필 UI 변경, 컴포넌트 분리
* 재사용하는 컴포넌트들 수정
* 해당 유저 정보 렌더링
.

[feat] 공개프로필 조회 추가

---

src/components/common/myProjectList/ProjectList.tsx

마이페이지, 공개프로필에서 프로젝트 리스트 데이터 없을 경우 메세지 추가작업
* 프로젝트 리스트 데이터 없을 경우 메세지 추가작업
.

[feat] 프로젝트 리스트 데이터 없을 경우 메세지 추가

---

src/components/common/SkillButton.tsx
src/components/login/SetProfile.tsx
src/components/mypage/CareerRadioInput.tsx
src/components/mypage/Careers.tsx
src/components/mypage/MyPageInfo.tsx
src/components/mypage/MyPageProfileImage.tsx
src/components/mypage/PositionCheckBox.tsx
src/components/mypage/ProfileImageModal.tsx
src/components/mypage/SkillList.tsx
src/components/mypage/TextInput.tsx
src/hooks/useUpdateProfile.ts
src/recoil/atoms.ts
src/utils/validation.ts

Closes #151 
Closes #149 
마이페이지 버그 해결과 마이페이지, 회원가입 닉네임 글자제한을 수정했습니다.
* 마이페이지 수정 완료 버튼 hover 시 텍스트 색상 수정
* 경력 체크 버튼 버그 수정 (onChange 이벤트 -> onClick 이벤트로 수정)
* 수정 완료 버튼 활성화, 유저 정보 state를 recoil state로 변경, 관련 파일들 수정
* 마이페이지 기술 스택 선택 시 수정완료 버튼 활성화 수정
* 닉네임, 이메일 유효성 검사 수정
* 닉네임 글자 제한 수정
.

[fix] 마이페이지 경력 수정 외 여러 버그 해결 

---

src/assets/styles/globalStyled.ts

Closes #137 
스크롤바 여부에 따른 헤더 덜컹거림 현상 수정을 작업했습니다.
* body에 `overflow: overlay` 추가
.

[fix] 스크롤바 여부에 따른 헤더 덜컹거림 현상 수정

---

src/components/ContentCard.tsx

팀원 찾기 카드 UI 스택 부분 디자인 변경
- 팀원 찾기 카드 UI 수정

[fix] 팀원 찾기 카드 UI 수정

---

src/components/common/myProjectList/ProjectList.tsx
src/pages/MyPage.tsx
src/pages/PublicProfilePage.tsx
src/utils/staleTime.ts

Closes #156 
마이페이지, 공개페이지에 stale time을 적용 했습니다.
* staleTime에 myprojects 추가
* 마이페이지, 공개프로필에 staleTime 적용
.

[fix] 마이페이지, 공개페이지 stale time 적용

---

src/components/login/LoginModal.tsx
src/components/login/SetPositions.tsx
src/components/login/SocialLogin.tsx

회원가입 모달 UI를 수정했습니다.
- 소셜 로그인 UI 수정
- 포지션, 경력 선택 UI 수정
.

[Feat] 회원가입 모달 UI 수정

---

src/components/main/Calendar/ProjectDetail.tsx

포지션이 0명일때도 나오는 로직을 수정
- 포지션 0명이 아닌 포지션만 보여주게 하는 로직으로 변경

[fix] 포지션 0명이 아닌 포지션만 보여주게 하는 로직으로 변경

---

src/components/popup/NotificationBox.tsx
src/components/popup/NotificationMessage.tsx
src/components/projectDetail/ApplyModal/ApplyButtonArea.tsx
src/components/projectDetail/ApplyModal/ApplyModal.tsx
src/components/projectDetail/InviteModals/InviteModal.tsx
src/hooks/useNotification.ts
src/pages/ProjectDetailPage.tsx
src/react-app-env.d.ts

Closes #169 
알림 보내기 기능을 추가했습니다.
- 프로젝트에 초대 되었을 경우 지원자에게 알림
- 신청한 프로젝트가 마감되었을 경우 지원자에게 알림
- 프로젝트 지원자가 생겼을 경우 글쓴이에게 알림
- 알림을 클릭하면 프로젝트 링크로 이동
.

[feat] 알림 보내기 기능 추가

---

src/apis/getPost.ts
src/components/main/recommendation/MainRecommendation.tsx

조회순/관심순 마감된 리스트도 나오는 이슈
- 조회순/관심순 모집중이면서 모집일 이내인 리스트로 필터링 변경

[fix] 조회순/관심순 마감 안된 프로젝트로 필터링

---

src/components/projectDetail/ContentArea.tsx
src/hooks/useEditBoard.ts
src/hooks/useWrite.ts
src/utils/validation.ts

Closes #127 
toast ui viewer 렌더링 에러를 수정하고, 제목/내용 유효성검사 minLength를 변경했습니다.
- toast ui viewr css 적용
- 유효성검사 최소 글자수 변경
.

[fix] toast ui viewer 렌더링 에러 수정

---

src/components/main/Calendar/ProjectDetail.tsx
src/components/main/banner/MainBanner.tsx

- 글이 길어지면 버튼이 UI가 깨지는 이슈
- button 위치  position: absolute로 변경

[fix] calendar detail button 위치 수정

---

src/components/popup/ReadInboxNote.tsx
src/components/popup/ReadOutboxNote.tsx
src/components/popup/styles.tsx
src/utils/modal.ts

쪽지 프로필 이미지 클릭 시 공개프로필로 이동하는 기능을 추가했습니다.
- 쪽지 프로필 이미지 클릭 시 공개프로필로 이동
.

[feat] 쪽지 프로필 이미지 클릭 시 공개프로필로 이동

---

src/components/main/banner/MainBanner.tsx

Closes #166 
화면이 작아졌을 때 슬라이더가 겹쳐 보이는 에러를 수정했습니다.
- 슬라이더에 overflow: hidden 속성 적용
- px -> rem 단위 변경
.

[fix] 슬라이더 width 에러 수정

---

src/components/popup/NoteBox.tsx
src/components/popup/NotificationBox.tsx
src/components/popup/styles.tsx

알림/쪽지 읽지 않은 메세지 수, 예외처리 문구를 추가했습니다.
- 알림/쪽지 디자인 변경
- 팝업창 타이틀에 읽지 않은 메세지 수 추가
- 데이터가 없을 경우 예외처리 문구 추가
.

[feat] 알림/쪽지 읽지 않은 메세지 수, 예외처리 문구 추가

---

src/components/popup/NotificationMessage.tsx
src/components/popup/styles.tsx

[fix] 알림 클릭 시 읽음 처리
안읽음 알림 클릭 시 읽음 처리하는 기능을 추가했습니다.
.

[fix] 알림 클릭 시 읽음 처리

---

src/components/common/Alert.tsx
src/components/projectDetail/MemberInfoArea.tsx
src/hooks/useWrite.ts
src/pages/ProjectDetailPage.tsx
src/routes/Router.tsx

배포 전 오류 수정
- 닉네임 호버기능 임시 제거
- 오타 수정
- 콘솔로그 제거

[PR] 1차 배포 전 수정

---

.eslintrc

build를 위한 eslintrc 설정을 제거했습니다.
- build를 위한 eslintrc 설정 제거

[fix] build를 위한 eslintrc 설정 제거

---

src/hooks/useSocialLogin.ts

회원가입시 쪽지 보내기 에러를 수정했습니다.
회원가입시 쪽지 보내기 로직 삭제
.

fix: 회원가입 시 쪽지보내기 에러 수정

---

src/components/editpage/mobile/EditPageMobileBody.tsx
src/components/editpage/mobile/EditPageMobileDeadline.tsx
src/components/editpage/mobile/EditPageMobileFooter.tsx
src/components/editpage/mobile/EditPageMobileHeader.tsx
src/components/editpage/mobile/EditPageMobilePeriod.tsx
src/components/editpage/mobile/EditPageMobilePosition.tsx
src/components/editpage/mobile/EditPageMobileStack.tsx
src/components/editpage/mobile/EditPageMobileThumbnail.tsx
src/components/writepage/mobile/WritePageMobileBody.tsx
src/components/writepage/mobile/WritePageMobileFooter.tsx
src/components/writepage/mobile/WritePageMobileHeader.tsx
src/hooks/useEditBoard.ts
src/pages/ProjectEditPage.tsx
src/pages/ProjectWritePage.tsx

글 수정 페이지 적응형 Mobile UI 작업 및 적용 데이터 뿌리기 작업
- 글 수정 Mobile 적응형 UI 작업
- 글 수정시 Default Value 값 가져오기
- editFormValue 값 데이터 수정 작업

[feat] 글 수정 적응형 Mobile UI 작업

---

src/components/mypage/LeftTab.tsx

회원 탈퇴 시 deleteDoc 부분을 임시 주석처리 했습니다.
* 회원 탈퇴 시 deleteDoc 부분을 임시 주석처리
.

fix: 회원 탈퇴 시 deleteDoc 임시 주석 처리

---

src/components/ContentCard.tsx
src/components/MobileContentCard.tsx
src/components/main/Calendar/ProjectCalendar.tsx
src/components/main/banner/MobileMainBanner.tsx
src/components/main/findUsers/MobileFindUserSlider.tsx
src/components/main/findUsers/MobileMainFindUsers.tsx
src/components/main/recommendation/MobileMainRecommendation.tsx
src/pages/MainPage.tsx

모바일 환경에서 main 화면 UI 구현
- mainPage Mobie과 web 구분하여 보이게 구현
- mobile banner UI
- Mobile Recommendation UI
- Mobile FindUsers UI
- Mobile FindUserSlider UI
- mobile banner 370 500 화면일때 배너 이미지 텍스트 크기 조정

[feat] 메인 페이지 mobile 화면 UI 

---

src/components/MobileContentCard.tsx
src/components/mypage/mobile/MobileMyPage.tsx
src/components/mypage/mobile/MobileProjectList.tsx
src/components/mypage/mobile/MobileSkillStackList.tsx
src/components/mypage/mobile/MobileUserInfo.tsx
src/components/writepage/mobile/WritePageMobileStack.tsx

Closes #201 
마이페이지 모바일 UI 기술스택, 프로젝트 리스트를 추가했습니다.
* 마이페이지 기술 스택 수정 추가]
* 모바일 마이페이지 프로젝트 리스트 추가
* 프로젝트 리스트 없을 경우 메시지 추가
* 수정 확인 모달창 모바일용으로 변경
.

[feat] 마이페이지 모바일 UI 추가 작업

---

src/components/MobileContentCard.tsx
src/components/main/banner/MobileMainBanner.tsx
src/components/main/recommendation/MobileMainRecommendation.tsx

프로젝트 찾기 이미지가 피그마랑 일치하게 구현
- 프로젝트 찾기 이미지 수정

[feat] 프로젝트 찾기 이미지 수정

---

src/components/common/mobile/MobileAlert.tsx
src/components/projectDetail/ApplicantCard.tsx
src/components/projectDetail/ApplicantListArea.tsx
src/components/projectDetail/ApplyModal/ApplyButtonArea.tsx
src/components/projectDetail/ApplyModal/ApplyModal.tsx
src/components/projectDetail/InviteModals/InviteModal.tsx
src/components/projectDetail/mobile/EndRecruitButton.tsx
src/components/projectDetail/mobile/MobileApplicantCard.tsx
src/components/projectDetail/mobile/MobileApplicantsList.tsx
src/components/projectDetail/mobile/MobileApplyButtonArea.tsx
src/components/projectDetail/mobile/MobileInviteModal/MobileInviteModal.tsx
src/components/projectDetail/mobile/MobileTitleThumbnailArea.tsx
src/components/projectDetail/mobile/projectDetailMobile.tsx
src/components/publicProfile/UserStacks.tsx
src/pages/ProjectDetailPage.tsx

모바일 전용 초대하기 모달 및 기능 구현
Fixes #223 
- 초대하기 모달 UI 구현
- 초대하기 모달 기능 구현
- 웹 버전 컴포넌트 분리

[PR] 모바일 초대하기 모달 UI 및 기능 구현

---

src/components/common/modal/ModalNavigator.tsx
src/components/login/SetProfile.tsx
src/components/login/mobile/MobileSetProfile.tsx
src/components/login/mobile/MobileSetSkillsPageStack.tsx
src/components/mypage/MyPageProfileImage.tsx
src/components/mypage/ProfileImageModal.tsx
src/components/mypage/TextInput.tsx
src/components/mypage/UserInfoTop.tsx
src/components/projectDetail/Likes.tsx
src/components/projectDetail/Share.tsx

Resolves #199 Resolves #216 
모바일 회원가입 UI를 수정했습니다.
- 회원가입 기술스택 UI 수정
- 회원가입 프로필 설정 UI 수정
- Share 컴포넌트 내 button 태그 중첩 에러 수정
.

[feat] 모바일 회원가입 UI 수정

---

src/apis/mypageUsers.ts
src/components/common/myProjectList/ProjectList.tsx
src/components/mypage/Careers.tsx
src/components/mypage/MyPageInfo.tsx
src/components/mypage/PositionCheckBox.tsx
src/components/mypage/ProfileImageModal.tsx
src/components/mypage/mobile/MobileMyPage.tsx
src/components/mypage/mobile/MobileUserInfo.tsx
src/hooks/useProfileImage.ts
src/hooks/useUpdateProfile.ts
src/pages/MyPage.tsx
src/react-app-env.d.ts

Fixes #208 
마이페이지 버그 수정 작업을 했습니다.
* 마이페이지에서 새로고침 시 로딩창 추가
* 프로젝트 리스트 없을 경우 포인터 default 설정
* 정보 수정 완료 버튼 활성화 버그 수정 (pc, mobile 둘 다 적용)
* 버튼 클릭 후 변경 확인 되었다는 Alert창으로 변경
* 프로필 사진 업로드 시 이미지 압축 추가
.

[fix] 마이페이지 버그 수정

---

src/components/common/LabelInput.tsx
src/components/editpage/mobile/EditPageMobileBody.tsx
src/components/editpage/mobile/EditPageMobileFooter.tsx
src/components/editpage/mobile/EditPageMobilePosition.tsx
src/components/editpage/mobile/EditPageMobileThumbnail.tsx
src/components/writepage/WritePagePosition.tsx
src/components/writepage/mobile/MobileInput.tsx
src/components/writepage/mobile/WritePageMobileBody.tsx
src/components/writepage/mobile/WritePageMobileFooter.tsx
src/components/writepage/mobile/WritePageMobilePosition.tsx
src/components/writepage/mobile/WritePageMobileThumbnail.tsx

#234 
- 글 작성 & 수정 Mobile Postion UI  디자인 완성
- 글 작성 & 수정 디자인 의도에 따른 Calcul 버튼 기능 구현
- 글 작성 & 수정 Mobile UI Design 완성
- Position 컴포넌트 로직이 길어짐에 따라 Input 분할 처리
- 글 작성 & 수정 디자인 의도에 따른 버튼에 따라 더하기 빼기 처리 기능 구현
- 글 작성 & 수정 썸네일 카메라 버튼 레이아웃 조정
- 글 작성 & 수정 버튼 maring-bottom 으로 밑 간격 띄우기
- 이 외 필요없는 로직 수정

[feat] 글 작성 & 수정 Mobile 적응형 UI 작업 및 기능 추가 작업

---

src/components/editpage/ProjectEditPageBody.tsx
src/components/editpage/mobile/EditPageMobileFooter.tsx
src/components/projectDetail/mobile/MobileTitleThumbnailArea.tsx
src/components/projectDetail/mobile/MobileWriterToProjectInfoArea.tsx
src/components/projectDetail/mobile/ModifyDeleteDropDown.tsx
src/components/publicProfile/mobile/MobilePublicProfilePage.tsx
src/components/publicProfile/mobile/PublicProfileImage.tsx
src/hooks/index.ts
src/pages/ProjectEditPage.tsx

Fixes #236 
Fixes #237 
- 공개 프로필 쪽지 보내기 아이콘 추가
- 공개 프로필 쪽지 모달 띄우기
- 프로젝트 상세보기 수정,삭제 드롭다운 추가
- 수정 페이지 연결
- 삭제 기능 추가

[PR] 프로젝트 상세보기, 공개프로필 모바일 UI 구현

---

src/components/MobileContentCard.tsx
src/components/ScrollToTopButton.tsx
src/components/findproject/mobile/FindProjectMobileList.tsx
src/components/main/findUsers/FindUserSlider.tsx
src/components/main/findUsers/MobileFindUserSlider.tsx
src/components/main/findUsers/MobileMainFindUsers.tsx
src/components/main/recommendation/MobileMainRecommendation.tsx
src/components/mypage/mobile/MobileProjectList.tsx
src/components/projectDetail/MemberInfoArea.tsx
src/components/projectDetail/WriterToShareArea.tsx
src/hooks/useSocialLogin.ts
src/pages/MainPage.tsx

모바일 메인페이지 UI를 수정했습니다.
- 메인페이지 UI 수정
- 스크롤투탑 버튼 UI 수정
- 사진, 데이터 없을 때 예외처리 UI 추가
.

[design] 모바일 메인페이지 UI 수정

---

src/components/popup/NoteModal.tsx
src/components/popup/ReplyNote.tsx
src/components/popup/mobile/MobileReplyNote.tsx

Closes #243 
답장하기를 할 때 받는 사람의 uid로 로그인한 사용자의 uid가 들어가는 에러를 수정했습니다.
- SendNote, ReplyNote 컴포넌트를 각각 분리
- ReplyNote에서 receiverUid를 변경
.

[fix] 쪽지보내기 receiver 에러 수정

---

src/components/common/mobile/MobileConfirmAlert.tsx
src/hooks/useEditBoard.ts
src/hooks/useWrite.ts
src/pages/ProjectWritePage.tsx

Closes #245 
- 글 작성이 2번 적용되던 현상 수정
- isSubmitting State를 통한 작성 시 버튼 중복클릭 방지 처리
- Code clean up

[fix] 글 작성 연속 클릭시 2번 작성되는 현상 수정

---

src/components/MobileFooter.tsx

모바일 푸터의 스타일드 컴포넌트 상속관련으로 에러 발생한 부분 해결
* 모바일 푸터 styled-components 오류 수정
.

[fix] 모바일 푸터 styled-components 오류 수정

---

src/apis/postDetail.ts
src/apis/userService.ts
src/components/projectDetail/ApplyModal/ApplyButtonArea.tsx
src/components/projectDetail/ApplyModal/ApplyModal.tsx
src/components/projectDetail/Likes.tsx
src/components/projectDetail/TitleThumbnailArea.tsx
src/components/projectDetail/WriterToShareArea.tsx
src/components/projectDetail/mobile/MobileTitleThumbnailArea.tsx
src/components/projectDetail/mobile/ModifyDeleteDropDown.tsx
src/hooks/useFindProject.ts

Close #239 
Close #240 
Close #260 
- 수정하기 페이지 데이터 전달 오류 수정
- 좋아요 기능 로직 수정(하루종일 걸림...)
- 삭제 후 메인 페이지 이동-> 이전 페이지로 이동
- 지원하기 모달 창 아니오 버튼 삭제

[PR] 프로젝트 상세보기 페이지 수정

---

src/apis/mypageUsers.ts
src/apis/postDetail.ts
src/components/common/myProjectList/ProjectList.tsx
src/components/projectDetail/TitleThumbnailArea.tsx
src/components/projectDetail/mobile/ModifyDeleteDropDown.tsx
src/pages/ProjectDetailPage.tsx
src/utils/staleTime.ts

Close #265 
- myproject에서 post에 있는 pid만 필터링을 시킨다.

[PR] 마이페이지, 공개프로필에서 사용하는 프로젝트 카드 오류 해결

---

src/components/editpage/mobile/EditPageMobilePeriod.tsx
src/components/editpage/mobile/EditPageMobileThumbnail.tsx
src/components/writepage/mobile/WritePageMobileDeadline.tsx
src/components/writepage/mobile/WritePageMobilePeriod.tsx
src/components/writepage/mobile/WritePageMobileThumbnail.tsx

- close #272 
웹에서 보는 모바일 UI와 핸드폰으로 보는 UI가 달라 이상한 부분 수정처리
- Mobile Date Input 기본 설정 값이 안보여 오늘 날짜로 Default 값 수정처리
- Mobile File Input 기본 설정 값과 파일 업로드시 파일 이름 안보이는 부분 보이도록 수정처리
- Mobile Thumbnail Button 핸드폰으로 보면 UI 뭉개지는 현상 수정처리

[feat] 모바일 환경의 날짜 인풋과 썸네일 인풋 수정

---

src/components/projectDetail/ApplicantCard.tsx
src/components/projectDetail/ApplyModal/ApplyButtonArea.tsx
src/components/projectDetail/ApplyModal/ApplyModal.tsx
src/components/projectDetail/ApplyModal/ApplyMotiveArea.tsx
src/components/projectDetail/ApplyModal/ApplyPositonArea.tsx
src/components/projectDetail/ContentArea.tsx
src/components/projectDetail/InviteModals/InviteModal.tsx
src/components/projectDetail/MemberInfoArea.tsx
src/components/projectDetail/ProjectInfoArea.tsx
src/components/projectDetail/Share.tsx
src/components/projectDetail/WriterToShareArea.tsx
src/components/projectDetail/mobile/MobileApplicantCard.tsx
src/components/projectDetail/mobile/MobileApplicantsList.tsx
src/components/projectDetail/mobile/MobileMemberInfoArea.tsx
src/components/projectDetail/mobile/MobileModal/MobileInviteModal.tsx
src/components/projectDetail/mobile/MobileRecruitContentArea.tsx
src/components/projectDetail/mobile/MobileTitleThumbnailArea.tsx
src/components/projectDetail/mobile/MobileViewsToShareArea.tsx
src/components/projectDetail/mobile/MobileWirterToProjectInfoArea.tsx
src/components/projectDetail/mobile/ModifyDeleteDropDown.tsx
src/components/publicProfile/UserPositions.tsx
src/components/publicProfile/UserStacks.tsx
src/components/publicProfile/mobile/MobilePublicProfilePage.tsx
src/components/publicProfile/mobile/PublicProfileImage.tsx
src/pages/MainPage.tsx
src/pages/ProjectDetailPage.tsx

현재 참여 중인 인원 개발 -> 프론트, 백엔드로 분리
Close #279  
- 컴포넌트 수정
- 마우스오버 효과 추가

[PR] 현재 참여 중인 인원 분리, 마우스오버 효과 추가

---

src/components/projectDetail/ApplyModal/ApplyModal.tsx
src/components/projectDetail/InviteModals/InviteModal.tsx
src/components/projectDetail/mobile/MobileModal/MobileInviteModal.tsx
src/pages/MainPage.tsx

Close #281 
- 초대하기 모달 스택이 없거나 넘칠 때 예외처리
- 모바일 백드랍 터치 시 모달 꺼지도록 수정

[PR] 초대하기 모달 수정

---

src/components/mypage/mobile/MobileProjectList.tsx

fix: 불필요한 로그 삭제

---

src/components/common/myProjectList/ProjectList.tsx
src/components/mypage/mobile/MobileProjectList.tsx

마이페이지 프로젝트 조회가 안 되는 오류 수정. 
프리뷰로 확인할 예정입니다.
개요와 같습니다
.

[fix] 마이페이지 프로젝트 리스트 조회 수정

---

src/apis/boardService.ts
src/apis/userService.ts
src/components/ContentCard.tsx
src/components/MobileContentCard.tsx
src/hooks/useFindProject.ts

close #287 
피드백에 따른 프로젝트 찾기에 Content Card 하트아이콘에 좋아요 기능 추가 및 애니메이션 효과 적용
- 좋아요 기능 로직 추가
- Content Card 전체 클릭에서 이미지 클릭시 디테일 페이지로 라우터 되도록 변경
- Content Card 하트 아이콘 호버시랑 클릭시 애니메이션 효과 적용
- Mobile Content Card에도 적용

[feat] 프로젝트 찾기 Card 좋아요 기능 추가 및 애니메이션 효과

---

src/components/ContentCard.tsx
src/components/MobileContentCard.tsx
src/components/editpage/ProjectEditPageBody.tsx
src/components/editpage/ProjectEditPageFooter.tsx
src/components/editpage/mobile/EditPageMobileFooter.tsx
src/components/editpage/mobile/EditPageMobileThumbnail.tsx
src/components/writepage/ProjectWritePageBody.tsx
src/components/writepage/mobile/WritePageMobileFooter.tsx
src/components/writepage/mobile/WritePageMobileThumbnail.tsx

- 글 작성 수정 버튼 호버효과 추가
- 전 Merge Vercel 프리뷰 버전에서 includes 예상 에러 수정 ( 로컬에선 안나고 프리뷰에서만 나는 에러라 확실치 않음)
- 웹 모바일 글 작성 수정 버튼 호버효과
- inCludes 에러 수정

[feat] 글 작성 & 수정 디자인 수정 및 에러 해결

---

src/components/ContentCard.tsx
src/components/MobileContentCard.tsx

로컬에선 정상 작동하는데 프리뷰에서 에러가 나는 현상 수정
- Content Card include Optional Chaining 적용

[feat] 프리뷰 버그

---

src/components/main/Calendar/MainCalendar.tsx
src/components/main/Calendar/ProjectDetail.tsx
src/pages/MainPage.tsx

- 메인페이지 캘린더 디테일 제목 깨지는 이슈
- 캘린더 디테일 제목 max-width 추가

[fix] 메인페이지 캘린더 디테일 제목 깨지는 이슈

---

src/components/common/myProjectList/ProjectList.tsx
src/components/main/Calendar/MainCalendar.tsx
src/components/mypage/mobile/MobileProjectList.tsx
src/components/projectDetail/TitleThumbnailArea.tsx
src/components/projectDetail/mobile/MobileApplicantCard.tsx
src/components/projectDetail/mobile/MobileApplicantsList.tsx

공개 프로필 undefined 오류 수정
- 오류를 수정한다.

[PR] 공개프로필 에러 수정

---

src/pages/MyPage.tsx
src/pages/PublicProfilePage.tsx

마이페이지, 공개프로필 페이지에 react-helmet을 이용해 메타태그를 추가했습니다.
- 마이페이지 메타태그 추가
- 공개 프로필 페이지 메타태그 추가
.

[feat] 마이페이지, 공개프로필 메타태그 적용

---

src/pages/MainPage.tsx

- 메인페이지 메타태그 적용
- 메인페이지 메타태그 적용

[Feat] 메인페이지 메타태그 적용

---

src/pages/ErrorPage.tsx
src/pages/ProjectDetailPage.tsx

상세보기 페이지, 에러 페이지에 메타태그를 적용했습니다.
* 상세보기 페이지, 에러 페이지 메타태그 적용
.

[feat] 상세보기 페이지, 에러 페이지 메타태그 적용

---

src/pages/ProjectDetailPage.tsx

썸네일이 존재하지 않을 때 기본 이미지를 표시하도록 메타태그를 수정했습니다.
- 썸네일이 존재하지 않을 때 기본 이미지를 표시
.

[fix] 썸네일이 존재하지 않을 때 메타태그 수정

---

src/apis/mypageUsers.ts
src/hooks/useEditBoard.ts
src/hooks/useProfileImage.ts
src/hooks/useWrite.ts

FileResize을 활용하여 webp 확장자로 자동 변환처리를 위한 작업
- FileResize 확장자를 webp로 변경하여 용량을 줄임

[fix] FileResize을 활용하여 webp 확장자로 자동 변환처리

---

src/components/Footer.tsx
src/components/Header.tsx
src/components/MobileHeader.tsx
src/components/mypage/MyPageInfo.tsx
src/components/mypage/mobile/MobileUserInfo.tsx
src/components/popup/mobile/MobileDropdownMenu.tsx
src/hooks/useProjectList.ts

amplitude 기능을 추가했습니다.
* pc, mobile 마이페이지 정보수정 버튼, 프로젝트 탭에 amplitude 추가
* pc, mobile 헤더에 amplitude 추가
* pc 푸터에 amplitude 추가 (모바일 해당 없음)
.

[feat] 마이페이지, 헤더, 푸터 amplitude 기능 추가

---

src/components/Header.tsx
src/components/popup/NoteMessage.tsx
src/components/popup/NotificationMessage.tsx
src/components/popup/ReplyNote.tsx
src/components/popup/SendNote.tsx
src/hooks/useSocialLogin.ts
src/utils/amplitude.ts

소셜로그인, 쪽지/알림 버튼 클릭 이벤트 로깅을 추가했습니다.
- amplitudeToNoneButtonClick 함수 추가
- 소셜로그인 버튼 클릭 이벤트 로깅
- 쪽지/알림 버튼 클릭 이벤트 로깅
.

[feat] 소셜로그인, 쪽지/알림 버튼 클릭 이벤트 로깅

---

src/components/main/Calendar/ProjectDetail.tsx
src/components/main/findUsers/FindUserSlider.tsx
src/components/main/findUsers/MobileFindUserSlider.tsx
src/components/main/recommendation/MainRecommendation.tsx
src/components/main/recommendation/MobileMainRecommendation.tsx

- 메인 페이지 Amplitude 코드 추가
- 메인 페이지 Amplitude 코드 추가

[feat]메인페이지 Amplitude 코드 추가

---

src/pages/MainPage.tsx

메인 페이지 title을 변경하는 helmet을 적용했습니다.
- 메인 페이지 title을 변경하는 helmet 적용
.

[feat] 메인페이지 Title Helmet 적용

---

src/components/projectDetail/ApplyModal/ApplyButtonArea.tsx
src/components/projectDetail/InviteModals/InviteModal.tsx
src/components/projectDetail/Likes.tsx
src/components/projectDetail/MemberInfoArea.tsx
src/components/projectDetail/Share.tsx
src/components/projectDetail/TitleThumbnailArea.tsx
src/components/projectDetail/WriterToShareArea.tsx
src/components/projectDetail/mobile/MobileMemberInfoArea.tsx
src/components/projectDetail/mobile/MobileModal/MobileInviteModal.tsx
src/components/projectDetail/mobile/MobileWirterToProjectInfoArea.tsx
src/components/projectDetail/mobile/ModifyDeleteDropDown.tsx
src/pages/ProjectDetailPage.tsx
src/pages/PublicProfilePage.tsx
src/utils/amplitude.ts

프로젝트 상세페이지, 공개프로필 클릭 이벤트 로깅을 위한 Amplitude를 적용하였습니다.
-amplitude 적용

[PR] 프로젝트 상세페이지, 공개프로필 Amplitude 적용

---

src/components/ScrollToTopButton.tsx

스크롤 투 탑 버튼 클릭 이벤트 로깅 기능을 추가했습니다.
- 스크롤 투 탑 버튼 클릭 이벤트에 amplitude 로그 추가
.

[feat] 스크롤투탑 버튼 클릭 이벤트 로깅

---

src/components/Footer.tsx
src/components/Header.tsx
src/components/mypage/CareerRadioInput.tsx
src/components/mypage/CheckboxButton.tsx
src/components/mypage/MyPageInfo.tsx
src/components/mypage/mobile/MobileUserInfo.tsx
src/components/popup/mobile/MobileDropdownMenu.tsx
src/hooks/index.ts
src/hooks/useGradient.ts
src/hooks/useHeader.ts

fix #322 
* 헤더,푸터와 마이페이지 코드 개선 작업을 했습니다.
* 비로그인일 경우 **새 글 쓰기** 를 누르면 로그인 모달창이 안 뜨던 버그도 해결했습니다. 
(제가 헤더쪽 이벤트 로깅 함수를 잘못 넣었던 것 같습니다 ㅠㅠ;)
* 헤더, 마이페이지, 푸터 이벤트 로깅 함수들을 `amplitudeToNoneButtonClick` 외 util에 추가된 함수로 변경
* 마이페이지 정보수정의 경력, 포지션 부분에 React.memo 적용
* 비로그인에서 새 글 작성 클릭 시 로그인 모달창 뜨지 않은 버그 수정
* useHeader 훅에서 그라디언트 관련 부분 useGradient 훅으로 분리
.

[fix] 헤더, 마이페이지 코드 개선

---

src/components/common/SkillButton.tsx
src/components/login/ConfirmButton.tsx
src/components/login/SetPositions.tsx
src/components/login/SetProfile.tsx
src/components/login/SetSkills.tsx
src/components/login/SetSkillsPageStack.tsx
src/components/login/mobile/MobileSetProfile.tsx
src/components/writepage/WritePageStack.tsx

회원가입 UI 수정사항을 반영했습니다.
- 포지션 선택 글자 wrap되는 현상 수정
- 포지션 선택 테두리 2px -> 1px 변경
- 스킬 선택 label 글자 크기 변경
- SkillButton이 선택되어 테두리가 생길 때  layout shift를 방지하기 위해 transparent border를 추가
.

[design] 회원가입 UI 수정사항 반영

---

src/components/projectDetail/ProjectInfoArea.tsx
src/components/projectDetail/TitleThumbnailArea.tsx
src/components/projectDetail/mobile/ModifyDeleteDropDown.tsx
src/pages/ProjectDetailPage.tsx

스택 디자인, 포지션 디자인을 수정하였습니다~
- 스택 아이콘 추가
- 포지션 구분선 수정
- 미선택 포지션 숨기기
- 미선택 스택 '협의가능' 문구 추가

[PR] 상세페이지 스택, 포지션 디자인 수정

---

src/components/ContentCard.tsx
src/components/MobileContentCard.tsx
src/components/main/banner/MainBanner.tsx
src/components/main/banner/MobileMainBanner.tsx
src/components/main/findUsers/FindUserSlider.tsx
src/components/main/findUsers/MobileFindUserSlider.tsx
src/components/popup/ReadInboxNote.tsx
src/components/popup/ReadOutboxNote.tsx
src/components/popup/ReplyNote.tsx
src/components/popup/SendNote.tsx
src/components/popup/mobile/MobileReadInboxNote.tsx
src/components/popup/mobile/MobileReadOutboxNote.tsx
src/components/popup/mobile/MobileReplyNote.tsx
src/components/popup/mobile/MobileSendNote.tsx
src/components/projectDetail/ApplicantCard.tsx
src/components/projectDetail/InviteModals/InviteModal.tsx
src/components/projectDetail/MemberInfoArea.tsx
src/components/projectDetail/TitleThumbnailArea.tsx
src/components/projectDetail/WriterToShareArea.tsx
src/components/projectDetail/mobile/MobileApplicantCard.tsx
src/components/projectDetail/mobile/MobileMemberInfoArea.tsx
src/components/projectDetail/mobile/MobileTitleThumbnailArea.tsx
src/components/projectDetail/mobile/MobileWirterToProjectInfoArea.tsx
src/components/publicProfile/mobile/PublicProfileImage.tsx
src/pages/ErrorPage.tsx

라이트 하우스에 따른 접근성 개선을 위해 모든 img 태그에 alt 속성을 추가했습니다
- img 태그 alt 속성 누락된 부분 모두 추가
.

[feat] img 태그에 누락된 alt 추가

---

src/components/ContentCard.tsx
src/components/MobileContentCard.tsx
src/components/editpage/EditPagePosition.tsx
src/components/editpage/ProjectEditPageBody.tsx
src/components/editpage/ProjectEditPageHeader.tsx
src/components/editpage/mobile/EditPageMobileBody.tsx
src/components/editpage/mobile/EditPageMobileDeadline.tsx
src/components/editpage/mobile/EditPageMobileHeader.tsx
src/components/editpage/mobile/EditPageMobilePeriod.tsx
src/components/editpage/mobile/EditPageMobilePosition.tsx
src/components/editpage/mobile/EditPageMobileThumbnail.tsx
src/components/findproject/FindProjectHeader.tsx
src/components/findproject/mobile/FindProjectMobileHeader.tsx
src/components/writepage/ProjectWritePageHeader.tsx
src/components/writepage/WritePageStack.tsx
src/components/writepage/mobile/WritePageMobileBody.tsx
src/components/writepage/mobile/WritePageMobileDeadline.tsx
src/components/writepage/mobile/WritePageMobileHeader.tsx
src/components/writepage/mobile/WritePageMobilePeriod.tsx
src/components/writepage/mobile/WritePageMobilePosition.tsx
src/components/writepage/mobile/WritePageMobileThumbnail.tsx
src/hooks/useEditBoard.ts
src/hooks/useFindProject.ts
src/hooks/useWrite.ts
src/pages/FindProjectPage.tsx
src/types/write/writeType.ts
src/utils/validation.ts

- 글 수정 & 작성, 팀원 찾기 페이지 타입 맞추기
- 글 수정 페이지 타입 작성
- 글 작성 페이지 타입 작성
- 팀원찾기 페이지 타입 작성

[fix] 글 수정 & 작성, 팀원 찾기 페이지 타입 맞추기

---

src/components/MobileContentCard.tsx
src/components/main/Calendar/ProjectCalendar.tsx
src/components/main/recommendation/MobileMainRecommendation.tsx

- 모바일 메인 디자인 수정
- 메인 디자인 수정
- 디자인 변경으로인한 디자인 수정 반영

[Feat] 메인 디자인 수정 반영

---

src/components/Header.tsx
src/components/common/myProjectList/ProjectList.tsx
src/components/popup/mobile/MobileDropdownMenu.tsx
src/pages/FindProjectPage.tsx

마이페이지 버그 수정 fix #336 
헤더 네비의 팀원 찾기 -> 프로젝트 찾기로 변경
* 프로젝트 아이템 props 중 pid 값 수정
* 헤더 네비바 텍스트 팀원찾기 -> 프로젝트 찾기로 수정
* 프로젝트 찾기 페이지 helmet 타이틀 수정 
.

[fix] 마이페이지 프로젝트 아이템 버그 수정, 헤더 네비바 수정 

---

src/components/ContentCard.tsx
src/components/findproject/FindProjectHeader.tsx
src/components/projectDetail/Likes.tsx
src/components/projectDetail/ProjectInfoArea.tsx
src/components/writepage/ProjectWritePageBody.tsx

접근성 개선을 위해 태그를 수정했습니다.
- [공통] Like 버튼에 id, aria-label 속성 추가
- [프로젝트 찾기] 모집 중 토글 버튼에 id, aria-label 속성 추가
- [프로젝트 상세보기] 스킬 버튼의 부모 태그를 ul로 변경
- [프로젝트 글쓰기] input 태그와 label 태그 연결
.

[feat] 접근성 개선을 위한 태그 수정

---

src/components/common/myProjectList/ProjectList.tsx
src/components/projectDetail/Likes.tsx
src/components/projectDetail/ProjectInfoArea.tsx
src/components/projectDetail/mobile/MobileWirterToProjectInfoArea.tsx

새로 게시글을 작성한 후에 마이페이지 작성한 글 목록에 업데이트가 되지 않는 오류를 수정하였습니다.
Close #331 
- 마이페이지 오류 수정
- 모집인원 세로 구분선 수정을 위한 map 함수 수정
- 필요스택 미선택 시 invisible

[PR] 새 게시글 작성 후 작성한 글 목록에 업데이트 되지 않는 오류 수정

---

src/components/login/SetPositions.tsx
src/components/login/SetSkills.tsx
src/components/login/mobile/MobileSetPositions.tsx
src/components/login/mobile/MobileSetSkills.tsx
src/components/popup/NoteMessage.tsx
src/components/popup/NotificationMessage.tsx
src/hooks/useNoteMessage.ts
src/hooks/useNotificationMessage.ts
src/hooks/useSetPositions.ts
src/hooks/useSetSkills.ts

로그인/회원가입, 알림/쪽지 커스텀훅을 추가하여 코드를 리팩토링 했습니다.
- `useSetPositions` 커스텀훅 추가 -> SetPositions, MobileSetPositions 컴포넌트에 적용
- `useSetSkills` 커스텀훅 추가 -> SetSkills, MobileSetSkills 컴포넌트에 적용
- `useNoteMessage`, `useNotificationMessage` 커스텀훅 추가 -> NoteMessage, NotificationMessage 컴포넌트에 적용
.

[refactor] 로그인/회원가입, 알림/쪽지 커스텀훅 추가

---

src/components/common/mobile/MobileAlert.tsx
src/components/projectDetail/Likes.tsx
src/components/writepage/mobile/WritePageMobileThumbnail.tsx

Fixes #341 
에러내용:  `FirebaseError: No document to update: projects/detto-1/databases/(default)/documents/post/LUULEONHAeJ4wSwrtdpc`
- 글 삭제 시에 삭제보다 언마운트가 먼저 발생하게되어 좋아요 mutate가 호출되어 발생하는 오류
- 이를 예외처리 하기 위해 setTimeout 1초를 걸어 삭제가 먼저 실시되도록 처리함

[PR] 글 삭제시 발생하는 버그 수정

---

src/components/common/LabelInput.tsx
src/components/editpage/EditPageDeadline.tsx
src/components/editpage/EditPagePeriod.tsx
src/components/editpage/EditPagePosition.tsx
src/components/editpage/EditPageStack.tsx
src/components/editpage/EditPageThumbnail.tsx
src/components/editpage/ProjectEditPageBody.tsx
src/components/editpage/ProjectEditPageHeader.tsx
src/components/editpage/mobile/EditPageMobileBody.tsx
src/components/editpage/mobile/EditPageMobileHeader.tsx
src/components/editpage/mobile/EditPageMobilePosition.tsx
src/components/editpage/mobile/EditPageMobileStack.tsx
src/components/writepage/ProjectWritePageBody.tsx
src/components/writepage/WritePageDeadline.tsx
src/components/writepage/WritePagePeriod.tsx
src/components/writepage/WritePagePosition.tsx
src/components/writepage/WritePageStack.tsx
src/components/writepage/WritePageThumbnail.tsx
src/components/writepage/mobile/WritePageMobileBody.tsx
src/components/writepage/mobile/WritePageMobilePosition.tsx
src/components/writepage/mobile/WritePageMobileStack.tsx
src/components/writepage/mobile/WritePageMobileThumbnail.tsx
src/hooks/useEditBoard.ts
src/hooks/useSelectEditStack.ts
src/hooks/useSelectStack.ts
src/hooks/useWrite.ts
src/pages/FindProjectPage.tsx
src/pages/ProjectEditPage.tsx
src/pages/ProjectWritePage.tsx

- 글 작성 페이지 컴포넌트 분리 및 Custom Hook 추가
- 글 수정 페이지 컴포넌트 분리 및 Custom Hook 추가
- 글 작성 & 수정 페이지 Position, Stack, Period, Deadline, Thumbnail 컴포넌트 분리
- 글 작성 & 수정 모바일 Position, Stack 컴포넌트 Custom Hook 분리
- 글 수정 Input Type 지정
- 이 외 Props 위치 수정 및 필요없는 코드 정리

[fix] 글 작성 & 수정 페이지 컴포넌트 분리 및 Custom Hook 추가

---

src/components/projectDetail/ProjectInfoArea.tsx
src/components/projectDetail/mobile/MobileWirterToProjectInfoArea.tsx

포지션 인원수가 변경되는 버그를 수정하였습니다.
map함수를 돌릴 때 순서가 지정되지 않은 객체를 써서 발생한 에러로
positionList를 사용하여 수정하였습니다.

[PR] 포지션 버그 수정

---

src/utils/validation.ts

- close #352 
글 작성 수정시 포지션 선택 두자릿수 이상 선택 못하게 적용
- 글 작성 포지션 99명 이상 금지

[fix] 글 작성 수정시 포지션 선택 두자릿수 이상 선택 못하게 적용

---

src/apis/postDetail.ts
src/components/projectDetail/Likes.tsx

setTimeout 설정 시 like 오류 발생하여 삭제합니다.
-setTimeout 삭제

fix: setTimeout 삭제

---

src/components/ContentCard.tsx
src/components/MobileContentCard.tsx

close #354 
Content Card 클릭시 라우팅 부분 개선
- Content Card PC 타이틀 클릭시에도 링크 이동
- Content Card Mobile 이미지 클릭시에도 링크 이동

[fix] 팀원찾기 페이지 Content Card Link 클릭 개선

---

src/components/mypage/mobile/MobileProjectList.tsx

Close #358 
- 게시글 작성시 마이페이지 작성한 글에 업데이트가 안되는 오류 수정
- 작성한 글의 인덱스 순서가 역순으로 돼있어, 선택한 글과 상세페이지의 글이 다른 오류를 수정하기 위해 배열 인덱스를 수정하였습니다.

[PR] 모바일 게시글 작성시 마이페이지 업데이트 오류

---

src/components/common/Alert.tsx
src/components/common/ConfirmAlert.tsx
src/components/common/mobile/MobileAlert.tsx
src/components/login/LoginModal.tsx
src/components/mypage/ProfileImageModal.tsx
src/components/popup/NoteModal.tsx
src/components/projectDetail/ApplicantCard.tsx
src/components/projectDetail/ApplyModal/ApplyModal.tsx
src/utils/modal.ts

Closes #356 
모달창이 열릴 때 헤더 배경이 투명해지는 버그를 해결했습니다.
- preventScroll 함수에서 body의 overflowY를 hidden으로 변경
- allowScroll 함수에서 body의 overflowY를 overlay(초기 상태)로 변경
.

[fix] 모달창이 열릴 때 헤더 배경이 투명해지는 버그 해결

---

src/components/projectDetail/ProjectInfoArea.tsx

유저 피드백 반영을 위해 프로젝트 상세페이지에 마감일을 추가하였습니다.
Closes #373 
- 마감일 추가

[PR] 프로젝트 상세페이지 마감일 추가

---

src/components/editpage/mobile/EditPageMobileBody.tsx
src/components/editpage/mobile/EditPageMobileDeadline.tsx
src/components/editpage/mobile/EditPageMobileFooter.tsx
src/components/editpage/mobile/EditPageMobileHeader.tsx
src/components/editpage/mobile/EditPageMobilePeriod.tsx
src/components/editpage/mobile/EditPageMobileThumbnail.tsx
src/components/main/banner/MobileMainBanner.tsx
src/components/projectDetail/mobile/MobileMemberInfoArea.tsx
src/components/projectDetail/mobile/MobileTitleThumbnailArea.tsx
src/components/projectDetail/mobile/MobileViewsToShareArea.tsx
src/components/projectDetail/mobile/MobileWirterToProjectInfoArea.tsx
src/components/writepage/mobile/WritePageMobileBody.tsx
src/components/writepage/mobile/WritePageMobileDeadline.tsx
src/components/writepage/mobile/WritePageMobileFooter.tsx
src/components/writepage/mobile/WritePageMobileHeader.tsx
src/components/writepage/mobile/WritePageMobilePeriod.tsx
src/components/writepage/mobile/WritePageMobileThumbnail.tsx
src/hooks/useIsMobile.ts
src/pages/FindProjectPage.tsx

Closes #372 
500~1200px 반응형 디자인을 적용했습니다.
- useIsMobile max-width를 1199px로 변경
- 메인페이지 배너 크기 수정
- 프로젝트 상세보기, 프로젝트 찾기, 프로젝트 작성/수정 디자인 수정
.

[feat] 500~1200px 반응형 디자인

---

src/apis/boardService.ts
src/components/findproject/FindProjectHeader.tsx
src/components/findproject/mobile/FindProjectMobileHeader.tsx

resolve #379 
resolve #380 
모집중 문구 변경과 무한 스크롤 버그를 수정 하였습니다.
- 모집중 문구 텍스트 수정
- 무한 스크롤 로직 수정

[fix] 모집중 문구 변경 & 무한 스크롤 버그 수정

---

src/components/ContentCard.tsx
src/components/MobileContentCard.tsx
src/utils/date.ts

Closes #376 
- 콘텐츠 카드 오른쪽 상단 마감일 띄우기 (데스크탑/모바일)
- 3일 이하로 남았을 경우 빨간색으로 강조
- D-day일 경우 마감일로 표시
- 마감된 프로젝트는 보여주지 않도록 수정

[PR] 콘텐츠 카드 오른쪽 상단 마감 D-day 띄우기

---

src/components/common/ApplyPositionButton.tsx
src/components/editpage/EditPageDeadline.tsx
src/components/editpage/EditPageStack.tsx
src/components/editpage/ProjectEditPageBody.tsx
src/components/projectDetail/MemberInfoArea.tsx

Closes #385 
- 마감된 게시글은 마감일 수정 못하도록 예외처리

[PR] 마감된 게시글 마감일 수정 못하도록 수정

---

src/components/mypage/LeftTab.tsx
src/components/mypage/TextInput.tsx
src/components/mypage/mobile/MobileUserInfo.tsx
src/hooks/index.ts
src/hooks/useWithdrawal.ts

Closes #383 
모바일 회원 탈퇴를 추가했습니다.
* 회원탈퇴 관련 로직 훅으로 분리
* 모바일 회원탈퇴 추가
.

[feat] 모바일 마이페이지 회원탈퇴 추가

---

src/components/projectDetail/ProjectInfoArea.tsx
src/components/projectDetail/mobile/MobileWirterToProjectInfoArea.tsx

[feat] 모바일 상세페이지 모집마감일 추가

---

src/components/ContentCard.tsx
src/components/MobileContentCard.tsx
src/components/projectDetail/ApplicantCard.tsx
src/components/projectDetail/ApplicantListArea.tsx

지원자 목록이 4명 이상일 경우 슬라이드가 보이도록 수정하였습니다.
하지만 슬라이더를 적용하였을 때 아래와 같이 z-index가 먹히지 않아 슬라이더 안에 모달이 묻히는 오류가 발생합니다.
현재 모달을 열 때 margin-bottom을 추가하는 방식으로 임시로 처리하였으나 수정이 필요할 것으로 보입니다.
- 프로젝트 상세보기 페이지 지원자 목록 4명 이상일 경우 슬라이드로 보여주기
- contentCard z-index 수정

[PR] 지원자목록 슬라이드로 수정

---

src/components/projectDetail/ContentArea.tsx
src/components/projectDetail/mobile/MobileRecruitContentArea.tsx

프로젝트 상세보기 Toast Editor CSS를 수정했습니다.
- heading - border bottom 삭제
- line height, padding, margin 수정
- list bullet, number 스타일 변경
.

[design] 프로젝트 상세보기 에디터 CSS 수정

---

src/components/projectDetail/MemberInfoArea.tsx

프로젝트 지원 후 닉네임 변경 시 반영이 안되기 때문에 닉네임 호버기능을 삭제했습니다.
- 닉네임 호버 기능 삭제

[PR] 닉네임 호버기능 삭제

---

src/components/main/recommendation/MobileMainRecommendation.tsx

- 모바일 환경에서의 더보기 버튼 피드백 변경 (버튼 처럼 보이게)
- 모바일 더보기 버튼 border border-radius 추가

[메인] 모바일 더보기 버튼 border border-radius 추가

---

src/components/ContentCard.tsx
src/components/projectDetail/MemberInfoArea.tsx

자동 마감이 안됐을 경우를 대비해 D-day 기능에 예외처리 하였습니다.
- d-day 수식 변경

[PR] 자동 마감 안될 경우 D-day 예외처리

---

src/components/TextEditor.tsx
src/components/projectDetail/ContentArea.tsx
src/components/projectDetail/mobile/MobileRecruitContentArea.tsx
src/components/writepage/ProjectWritePageFooter.tsx
src/components/writepage/mobile/WritePageMobileFooter.tsx

프로젝트 글 작성/수정 페이지 에디터 CSS를 수정했습니다.
- TextEditor 컴포넌트에 스타일 적용
.

[feat] 프로젝트 글 작성/수정 페이지 에디터 CSS 수정

---

src/components/common/myProjectList/ProjectItem.tsx
src/components/common/myProjectList/mobile/MobileProjectListTab.tsx
src/components/mypage/mobile/MobileTopTab.tsx
src/components/mypage/mobile/MobileUserInfo.tsx
src/components/publicProfile/UserStacks.tsx
src/hooks/useUpdateProfile.ts

Closes #412 
* 프로젝트 아이템 기술스택 부분 포인터 추가
* 마이페이지 반응형 시 누락된 포인터 추가 (회원탈퇴, 정보수정 버튼, 탭 등)
* 마이페이지 닉네임 수정 시 공백 입력했을 경우에도 토스트 팝업 뜨도록 변경
.

[fix] 마이페이지 커서 버그

---

src/components/main/Calendar/ProjectList.tsx
src/components/main/banner/MainBanner.tsx

- 배너가 너무 크다는 피드백을 받고 30% 줄임
- 기획 0 | 디자인너 0 | 개발 0 예외 처리
- 배너가 너무 크다는 피드백을 받고 30% 줄임
- 기획 0 | 디자인너 0 | 개발 0 예외 처리

[메인] 배너 크기 30% 줄이고 , 모집인원 예외 처리

---

src/apis/boardService.ts
src/components/writepage/WritePageDeadline.tsx
src/utils/date.ts

마감시간을 23시 59분에서 23시 59분 59초로 변경하였습니다.
D-day 계산 함수 변경이 필요하여 수정하였습니다.
개요와 같음

[PR] 마감시간 변경, d-day 남은 일수 계산 함수 수정

---

src/components/main/banner/MainBanner.tsx

메인페이지 배너가 움직이지 않는 에러를 수정했습니다.
* video 옵션에 muted 추가
.

[fix] 메인페이지 배너 움직이지 않는 에러 수정

---

src/apis/userService.ts
src/components/main/findUsers/FindUserSlider.tsx
src/components/main/findUsers/MobileFindUserSlider.tsx
src/utils/staleTime.ts

메인 페이지 랜던 팀원 슬라이드를 수정했습니다.
- (기존) 포지션 선택 할때마다 random 정렬 -> (변경) firebase에서 불러올 때 한번만 random 정렬
- randomUsers staleTime 10분 적용
- 쿼리키 'random' 추가
.

[feat] 메인페이지 랜덤 팀원 슬라이드 수정

---

src/components/ContentCard.tsx
src/components/MobileContentCard.tsx
src/components/findproject/FindProjectList.tsx
src/components/findproject/mobile/FindProjectMobileList.tsx
src/components/projectDetail/Likes.tsx
src/components/projectDetail/WriterToShareArea.tsx
src/components/projectDetail/mobile/MobileViewsToShareArea.tsx
src/pages/FindProjectPage.tsx

ContentCard와 상세페이지의 좋아요가 연동되지 않아 컴포넌트를 통일하였습니다.
개요와 같음

[PR] ContentCard에 좋아요 컴포넌트 적용

---

src/apis/userService.ts
src/components/main/findUsers/FindUserSlider.tsx
src/components/main/findUsers/MobileFindUserSlider.tsx
src/utils/staleTime.ts

Revert "[feat] 메인페이지 랜덤 팀원 슬라이드 수정"

---

src/apis/userService.ts
src/components/main/findUsers/FindUserSlider.tsx
src/components/main/findUsers/MobileFindUserSlider.tsx
src/utils/staleTime.ts

메인 페이지 랜던 팀원 슬라이드를 수정했습니다.
- (기존) 포지션 선택 할때마다 random 정렬 -> (변경) firebase에서 불러올 때 한번만 random 정렬
- randomUsers staleTime 10분 적용
- 쿼리키 'random' 추가
.

feat: 랜덤 팀원 슬라이드 limit, staleTime 수정

---

src/components/findproject/FindProjectList.tsx
src/components/projectDetail/mobile/MobileApplicantCard.tsx

Sentry에서 모니터링 한 타입 에러를 수정하기 위해 옵셔널 체이닝을 추가하였습니다.
이슈 내용

[PR] Sentry에서 모니터링된 타입 에러 수정

---

src/components/projectDetail/WriterToShareArea.tsx
src/components/projectDetail/mobile/MobileWirterToProjectInfoArea.tsx
src/components/publicProfile/mobile/PublicProfileImage.tsx

유저 피드백 반영하기 위해 상세 페이지의 작성자 닉네임 옆 쪽지 아이콘을 추가하였습니다.
- 모바일
- 데스크탑

[PR] 상세 페이지 작성자 닉네임 옆 쪽지 아이콘 추가

---

README.md

main 브랜치가 보호되고 있어서 PR 작성합니다 ^^..
* 리드미 수정
.

[docs] 리드미 업데이트

---

src/hooks/useEditBoard.ts
src/hooks/useWrite.ts

글 작성하거나 수정시 저장이 안된다는 경고 알람 추가
- 새로고침 이벤트 감지 로직 추가
- 새로고침시 알람 로직 적용

[feat] 글 작성 & 수정 새로고침시 경고 알람 문구 추가

---

src/apis/findWithCollectionName.ts
src/apis/mypageUsers.ts
src/apis/notes.ts
src/apis/postDetail.ts
src/components/common/myProjectList/ProjectList.tsx
src/components/main/Calendar/ProjectCalendar.tsx
src/components/projectDetail/ApplicantCard.tsx
src/utils/skills.ts

any 타입으로 지정되어 있던 일부 코드를 수정했습니다.
개요와 동일
.

[fix] any 타입 일부 수정

---

src/components/main/Calendar/ProjectCalendar.tsx
src/components/main/Calendar/ProjectDetail.tsx

- any인 타입을 최대한 추론해서 타입 지정하기
- 메인페이지 type 추론후 지정

[메인] type 추론후 지정

---

src/apis/findWithCollectionName.ts
src/apis/mypageUsers.ts
src/apis/notifications.ts
src/components/projectDetail/Views.tsx
src/hooks/useNote.ts
src/hooks/useProfileImage.ts
src/react-app-env.d.ts
src/utils/amplitude.ts

TypeScript any type을 수정했습니다.
- TypeSCript any type 수정
.

[fix] any type 수정

---

src/pages/ErrorPage.tsx
src/pages/Root.tsx
src/routes/Router.tsx

모바일 에러 페이지를 추가했습니다.
- ErrorPage 컴포넌트 isMobile 상태에 따라 크기 조정
.

[feat] 모바일 에러 페이지 추가

---

src/components/login/LoginModal.tsx

LoginModal의 cyclic dependency 에러를 수정했습니다.
- LoginModal 컴포넌트를 함수 선언식으로 변경
.

[fix] LoginModal 함수 선언식으로 변경

---

src/components/projectDetail/TitleThumbnailArea.tsx
src/components/projectDetail/mobile/ModifyDeleteDropDown.tsx

모바일에서 수정 후 삭제 시 수정페이지로 이동하는 오류를 예외처리하였습니다.
개요와 같음

fix: (모바일) 수정 후 삭제 시 발생하는 오류 예외처리

---

README.md

README 로고를 브로셔 이미지로 변경했습니다.
- RAEDME 로고 변경

[docs] README 로고 변경

---

src/components/projectDetail/ApplicantCard.tsx
src/components/projectDetail/ApplicantListArea.tsx
src/components/projectDetail/ApplyButtonArea.tsx
src/components/projectDetail/InviteModals/InviteModal.tsx
src/components/projectDetail/MemberInfoArea.tsx
src/components/projectDetail/ParticipantsProfile.tsx
src/components/projectDetail/mobile/MobileMemberInfoArea.tsx
src/components/projectDetail/mobile/MobileModal/MobileInviteModal.tsx
src/hooks/useNotification.ts
src/react-app-env.d.ts

지원자 정보 데이터 구조 변경 이후 undefined 에러가 발생하여 로직을 수정했습니다.
- participantsData에 uid와 position을 함께 저장
.

[fix] 지원자 정보 undefined 에러 수정
