Team-Detto/Detto

src/components/Header.tsx
src/routes/Router.tsx

헤더 UI를 완성하기 위한 PR입니다.
* 헤더 UI 추가
* 페이지 이동 링크 설정 
* 메인페이지일 경우 헤더 배경 그라데이션 설정
* 메인페이지일 경우 하단으로 스크롤 시 특정영역(현재는 700px로 설정)을 벗어나면 배경 하얀색 고정
.

[feat] 헤더 UI 및 인터랙션 추가

---

src/components/Header.tsx
src/pages/MainPage.tsx

현재 메인페이지에서의 헤더 배경색이 배너 영역을 벗어 났을 때도 투명한 이슈, 
네비게이션에 마이페이지, 로그아웃 같은 빠진 UI 요소를 추가작업한 PR입니다.
* 메인 페이지 헤더 배경색 변환 이슈 해결
* 배경색 변환 시점 높이값 수정, 높이값 상수화
* nav에 마이페이지, 로그아웃 추가 (현재는 주석처리)
.

[fix] 헤더 UI 수정

---

src/App.tsx
src/components/login/LoginPage0.tsx
src/hooks/useSocialLogin.ts

GitHub, Google 소셜 로그인 기능을 추가했습니다.
(Kakao는 추가 구현 예정)
- `useSocialLogin` 훅 생성
- GitHub, Google 소셜 로그인
- 로그인 완료 후 user 객체를 `로컬스토리지`에 저장
.

[feat] GitHub, Google 소셜 로그인 기능 추가

---

src/assets/styles/globalStyled.ts
src/components/Header.tsx
src/hooks/index.ts
src/hooks/useHeader.ts

Closes #78 
헤더에 로그인 여부 반영 작업을 했습니다.
* 로그인, 비로그인 여부에 따른 헤더 내비게이션 요소 변경 적용
* 로그아웃 기능 추가
* 헤더 CSS 변경 (피그마 따라서 배경 그라데이션 색상 변경, 메뉴에 hover 적용)
* 헤더 메뉴 클릭 시 페이지 이동 후에도 active 상태 유지하도록 적용
* 헤더 관련 로직 useHeader로 분리, useAuth 적용
* 이미지 드래그 잔상방지 GlobalStyles에 적용 
.

[fix] 헤더 내비게이션 로그인 여부 반영

---

src/components/Header.tsx
src/hooks/usePopup.ts

기존에 페이지 이동 시 알림/쪽지 팝업창이 닫히지 않아, 닫기 기능을 추가했습니다.
- usePopup 커스텀 훅 `closePopup` 함수 추가
- Header 컴포넌트 내에서 `pathname`이 변경되면 closePopup 호출
.

[feat] 페이지 이동 시 알림/쪽지 팝업창 닫기 기능 추가

---

src/apis/postDetail.ts
src/components/projectDetail/ApplicantListArea.tsx
src/components/projectDetail/ApplyButtonArea.tsx
src/components/projectDetail/WriterToShareArea.tsx
src/components/projectDetail/modals/ApplyModal.tsx
src/components/projectDetail/modals/InviteModal.tsx
src/pages/ProjectDetailPage.tsx

#68 번째 Issue 고치는 중
- 데이터 구조의 이상을 느끼고 구조 변경을 시도함
[기존]
- applicants에 map으로 데이터를 넣어 두고 지원자 목록을 관리
- 작성자가 초대하기 버튼 클릭 시 applicants에서 데이터를 삭제하고 participants에 데이터를 삽입함
[수정]
- applicants map에 recruit<boolean> 항목을 추가하여 지원만 했을 땐 false, 초대받았을 땐 true로 수정하도록 구현함
- map 형식의 배열에서 map 형식의 map으로 수정하여 applicants:{[uid]: {data}}의 구조를 가짐

[PR] 지원자 목록 데이터 구조 변경

---

src/apis/postDetail.ts
src/components/projectDetail/ApplicantListArea.tsx
src/components/projectDetail/ApplyButtonArea.tsx
src/components/projectDetail/Likes.tsx
src/components/projectDetail/MemberInfoArea.tsx
src/components/projectDetail/WriterToShareArea.tsx
src/components/projectDetail/modals/ApplyModal.tsx
src/components/projectDetail/modals/InviteModal.tsx
src/pages/ProjectDetailPage.tsx

Fixes #111 
- 지원 완료 시 myproject 컬렉션의 appliedProjects에 데이터가 들어간다.
- 초대 완료 시 myprojcet 컬렉션의 appliedProjects의 recruited의 데이터가 false에서 true로 바뀐다.
- 지원자 목록에서 스택 두 줄로 변경
- 지원하기 모달에서 보여주는 스택 개수 제한
- 하트 아이콘 변경
- 좋아요 로직 수정
@yujleee 혹시 appliedProjects 이 부분 map 돌려보시고 문제가 되면 얘기해주세요!!
데이터 구조:  appliedProjects: {[pid]: recruited}}
recruited<boolean> false면 초대 전 true면 초대완료

[PR] 프로젝트 지원, 초대 시 데이터베이스에 값 넣기

---

src/apis/postDetail.ts
src/components/ContentCard.tsx
src/components/projectDetail/ApplyButtonArea.tsx
src/hooks/useModal.ts
src/pages/ProjectDetailPage.tsx

- 프로젝트 상세 보기 비작성자일 경우 지원 신청 / 지원 취소 구분
- 프로젝트 상세 보기 작성자일 경우 모집완료 / 모집마감 구분
- 각각에 상황에 따라 Alert 생성
- Firebase 프로젝트 지원자인지 확인 여부 로직 작성
- useModal 여러개일 경우 ! 인자 에러나서 True False 고정 값 함수 생성
- 지원 & 마감 데이터 얻어와서 각각 화면에 맞는 Alert 타이틀과 메시지 보여주기
- 프로젝트 찾기 썸네일 이미지 fit으로 수정

[feat] 프로젝트 상세 보기 모집 & 지원 기준확인 및 Alert 생성

---

src/components/popup/NotificationBox.tsx
src/components/popup/NotificationMessage.tsx
src/components/popup/styles.tsx

알림창을 클릭 시 안읽은 메세지를 모두 읽음 상태로 변경하는 기능을 추가했습니다.
- 알림창 클릭 시 모두 읽음 처리
.

[feat] 알림창 클릭 시 알림 모두 읽기

---

src/components/mypage/MyPageInfo.tsx
src/components/mypage/UserInfoTop.tsx
src/hooks/useUpdateProfile.ts
src/pages/MyPage.tsx

Closes #158 
유저 정보 수정 후 버튼 클릭 시의 유효성 검사 확인 로직이 누락되어 추가했습니다.
이메일 같은 경우는 null 값이 허용되기 때문에 (깃허브 가입 시 null인 경우 있음)
빈 값일 경우의 처리가 어려워서 유효한 이메일인지 확인하도록 했습니다.
* 아무것도 수정하지 않았다면 수정버튼 disabled 처리
* 완료 버튼 클릭 시 닉네임 / 이메일 / 포지션 유효성 검사에 따라 toast 팝업 보여주기
.

[fix] 유저 정보 수정 후 버튼 클릭 시의 유효성 검사 확인 추가

---

src/App.tsx
src/apis/postDetail.ts
src/components/Header.tsx
src/components/projectDetail/ApplyButtonArea.tsx
src/components/projectDetail/Likes.tsx
src/hooks/index.ts
src/hooks/useFindProject.ts
src/hooks/useIsLogin.ts
src/pages/PublicProfilePage.tsx
src/pages/Root.tsx
src/routes/Router.tsx
src/utils/modal.ts

Closes #175 
로그인 권한 예외처리 기능을 추가했습니다.
- 로그인 권한에 따라 페이지 라우팅 (마이페이지, 글쓰기/수정 접근 시 홈으로 리다이렉션)
- 로딩/에러 페이지에서 헤더 보여주기
- 로그인 안 된 상태에서 firebase 유저 컬렉션 조회 제한
- 로그인이 필요한 기능 클릭 시 로그인 모달창 열기 (쪽지 보내기, 프로젝트 지원하기, 새글쓰기)
.

[feat] 로그인 권한 예외처리

---

src/components/editpage/ProjectEditPageBody.tsx
src/components/writepage/ProjectWritePageBody.tsx
src/hooks/useEditBoard.ts
src/hooks/useWrite.ts
src/pages/ProjectEditPage.tsx
src/types/write/writeType.ts

Closes #182 
썸네일 이미지 업로드시 버튼 색상 변경처리 및 Input file 타입의 확장자를 고정 했습니다. 
- 썸네일 이미지 업로드 onChagne와 State처리를 통해 렌더링시켜 버튼 색상처리
- Input type file의 Option accept를 이용해 jpg, png, jpeg 확장자만 올라오도록 수정

[fix] 썸네일 이미지 업로드 버튼 색상 처리 & 확장자 고정

---

src/apis/boardService.ts
src/components/editpage/ProjectEditPageBody.tsx
src/components/writepage/ProjectWritePageBody.tsx
src/hooks/useEditBoard.ts
src/hooks/useWrite.ts
src/pages/ProjectEditPage.tsx
src/pages/ProjectWritePage.tsx

무한 스크롤 기본 불러오기 값 15개로 수정
- firebase 무한 스크롤 default Limit(15)로 수정 
- body안 function hooks로 분리

[fix] 무한 스크롤 기본 불러오기 값 15개로 수정

---

src/components/Header.tsx
src/components/MobileHeader.tsx
src/hooks/useHeader.ts

Closes #197 
헤더 모바일 UI를 추가했습니다.
기존 헤더의 onClick 이벤트, 링크 등 거의 적용해놓았고, 
로그인, 쪽지 등의 모달창, 팝업들은 모바일에 맞게 달라지는 부분들을 추가적으로 수정해주시면 될 것 같습니다.
(쪽지, 알람 카운트는 일단 UI 잡아두고 기존 로직을 적용 해놓았는데 추가 수정이 필요할 것 같습니다. 👀)
* 모바일 헤더 UI 컴포넌트 추가
* 뒤로가기 기능 추가
* 기존 onClick 이벤트 등 적용
.

[feat] 헤더 모바일 UI 추가

---

src/components/MobileContentCard.tsx
src/components/MobileHeader.tsx
src/components/mypage/mobile/MobileUserInfo.tsx
src/components/popup/mobile/MobileDropdownMenu.tsx
src/hooks/usePopup.ts
src/recoil/atoms.ts

Fixes #227, Fixes #225 
모바일 마이페이지, 헤더 버그 수정 작업을 했습니다.
마이페이지 정보 수정 버튼 활성화 부분은 pc버전은 작업을 모바일에도 반영할 예정입니다. (내일 아침 공유 예정)
* 모바일 마이페이지 정보수정 가운데로 오도록 너비 수정
* 헤더 드롭다운 메뉴 다른 영역 누르면 창 닫히도록 수정
* 프로젝트 리스트(마이페이지, 공개프로필)에 하트 반영 안 되던 부분 수정 
.

[fix] 모바일 마이페이지, 헤더 버그 수정

---

src/components/login/Welcome.tsx
src/components/login/mobile/MobileWelcome.tsx
src/components/mypage/LeftTab.tsx
src/hooks/useHeader.ts
src/hooks/useSocialLogin.ts
src/hooks/useUpdateProfile.ts

fix #233 
로그인/로그아웃 시의 렌더링 버그 해결을 위한  작업을 진행했습니다.
현재 배포 된 링크에서 로그인 시 바로 마이페이지, 새 글 쓰기에 접근할 수 없는 이슈 
로그아웃 후 다른 계정으로 로그인 한 뒤 마이페이지 갔을 때 이전 계정의 정보가 보여지는 이슈
프리뷰로 테스트해볼 예정입니다.
* 로그인/회원가입 시 모달창 닫힌 후 새로고침 추가
* 로그아웃 시 새로고침 추가
* 회원탈퇴 로직 수정
* 로그아웃/회원탈퇴 시 마이페이지에서 사용되는 userInfo state를 초기값으로 변경
.

[fix] 로그인/로그아웃 시 렌더링 버그 수정

---

src/components/main/Calendar/ProjectList.tsx

메인 페이지 캘린더에 선택된 데이터가 없을때 NO DATA 문구를 추가했습니다.
- ProjectList 컴포넌트에서 dayList의 길이가 0일 때 NodataMessage 반환
.

[feat] 캘린더 데이터가 없을 때 nodata 문구 표시

---

src/components/ContentCard.tsx
src/components/MobileContentCard.tsx
src/components/common/mobile/MobileContainer.tsx
src/components/main/Calendar/ProjectDetail.tsx
src/components/main/Calendar/ProjectList.tsx
src/components/projectDetail/mobile/MobileRecruitContentArea.tsx
src/components/writepage/mobile/WritePageMobileFooter.tsx
src/components/writepage/mobile/WritePageMobileHeader.tsx
src/components/writepage/mobile/WritePageMobileThumbnail.tsx

- 모바일 상세보기 페이지 Toast UI Viewer를 적용했습니다.
- 제목이 길어질 경우 ellipsis를 적용했습니다.
- ContentArea 컴포넌트에 Viewer 추가
- Project List, Content Card, Calendar 제목 ellipsis 추가
.

[feat] 모바일 상세보기 Viewer, 제목 ellipsis 적용

---

src/components/projectDetail/ContentArea.tsx
src/components/projectDetail/mobile/MobileRecruitContentArea.tsx

- close #258 
- 디테일 페이지에서 Toast Ui Editor 의 Viewer 컴포넌트가 글 수정시 수정한 Content 값으로 제대로 안나오는 렌더링 문제 해결을 위한 이슈
- 디테일 페이지 Toast Ui Editor 기본 폰트 사이즈 변경
- 디테일 페이지 ContentArea 부분 렌더링 늦추기
- 디테일 페이지 Toast Ui Editor CSS 세부 조정을 통해 기본 폰트 사이즈 키우기

[fix] 디테일 페이지 toast ui editor 수정시 바로 값 안바뀌는 버그 수정

---

src/apis/userService.ts
src/components/main/findUsers/FindUserSlider.tsx
src/components/main/findUsers/MobileFindUserSlider.tsx
src/components/mypage/LeftTab.tsx
src/components/popup/CustomButton.tsx
src/components/popup/ReadInboxNote.tsx
src/components/popup/mobile/MobileCustomButton.tsx
src/components/popup/mobile/MobileReadInboxNote.tsx
src/hooks/useSocialLogin.ts
src/pages/PublicProfilePage.tsx
src/react-app-env.d.ts

회원 탈퇴 기능을 구현했습니다.
- 사용자 문서에 isActive 필드를 추가했습니다.
- 회원 탈퇴 시 isActive를 false로 수정했습니다.
- 탈퇴한 유저의 공개프로필에 접근 시 에러 메세지를 추가했습니다.
- 탈퇴한 유저의 쪽지에 답장하기 버튼을 비활성화 했습니다.
.

[feat] 회원탈퇴 기능 구현

---

src/components/popup/ReplyNote.tsx
src/components/popup/SendNote.tsx

Closes #305 
유효성 검사 실패 시 쪽지 보내기 버튼이 disabled 되는 에러를 수정했습니다.
쪽지 보내기 버튼의 onClick 이벤트에서 setDisabled 제거
.

[fix] 유효성 검사 실패 시 버튼 disabled되는 에러 수정

---

src/components/ContentCard.tsx
src/components/MobileContentCard.tsx
src/hooks/useEditBoard.ts
src/hooks/useFindProject.ts
src/hooks/useWrite.ts
src/pages/FindProjectPage.tsx

팀원찾기 페이지와 글 작성 수정 페이지에 유저 사용성 체크를 위한 Amplitude 적용
- 글 작성 & 수정 버튼 클릭 로직에 Amplitude 적용
- 팀원 찾기 페이지 카테고리, 토글버튼, 좋아요버튼, content card에 Amplitude 적용

[feat] 팀원찾기, 글 작성&수정 Amplitude 적용

---

src/components/ContentCard.tsx
src/components/MobileContentCard.tsx
src/components/projectDetail/ApplyModal/ApplyModal.tsx
src/components/projectDetail/ApplyModal/ApplyModalButtonArea.tsx
src/components/projectDetail/Likes.tsx
src/components/projectDetail/Share.tsx
src/hooks/useFindProject.ts
src/index.tsx
src/pages/MyPage.tsx
src/pages/ProjectDetailPage.tsx
src/pages/PublicProfilePage.tsx
src/utils/staleTime.ts

React Query 에러를 해결하고, staleTime을 조정했습니다.
- 로그인하지 않은 상태에서 ContentCard 클릭 시 로그인 모달을 띄우는 로직 추가
- useQuery 옵션에 enabled 추가하여 params가 존재하지 않을 때 disabled 처리
- defaultOptions의 staleTime 제거 (모든 쿼리에 staleTime이 덮어씌워지고 있어서 삭제했습니다.)
- 전체 유저, 인기 포스트 staleTime을 늘렸습니다.

[fix] react query 에러 해결 & staleTime 조정

---

src/hooks/useProjectList.ts

마이페이지, 공개프로필의 프로젝트 리스트를 최신 순으로 나열하도록 작업했습니다.
(현재에는 정렬 기준이 과거->최근 순이라 최근에 작성한/지원한/관심있는.. 프로젝트가 가장 밑에 보이는 상태 였습니다!)
* 프로젝트 리스트를 최신 순으로 나열하도록 pid 리스트를 뒤집어서 반환하도록 변경
.

[fix] 마이페이지, 공개프로필 프로젝트 리스트 최신순 변경

---

src/components/projectDetail/mobile/MobileTitleThumbnailArea.tsx

모바일 프로젝트 상세보기 페이지 디자인을 수정했습니다.
- 기본 썸네일 이미지 추가
- 제목 글자수가 두줄 이상 넘어가면 ellipsis 적용
- 모집중 최소너비 적용
.

[fix] 모바일 프로젝트 상세보기 디자인 수정

---

src/components/ContentCard.tsx
src/components/MobileContentCard.tsx

Close #360 
Content Card에서 좋아요 버튼 클릭시 Mypage 관심 프로젝트에 새로고침 할 때만 반영되는 버그 처리
- Content Card `useMuate`에 Mypage query key `Query invalidate`처리

[fix] Content Card 좋아요 클릭시 query invalidate 처리

---

src/components/projectDetail/Likes.tsx

close #360 
디테일 페이지 좋아요 버튼 클릭시 Content Card에 있는 하트 아이콘에 바로 적용 안되는 현상 수정
- 디테일 페이지에서 좋아요 버튼 클릭시 팀원찾기 페이지에서 받아오는 데이터 invalid 처리

[fix] 디테일 페이지에서 좋아요 클릭시 Content Card에 반영 안되는 현상 수정

---

src/components/popup/NoteMessage.tsx
src/hooks/useNoteMessage.ts

Closes #364 
보낸 쪽지함에서 받는 사람 닉네임을 표시하도록 수정했습니다.
- `useNoteMessage` 커스텀훅에서 inbox일 경우 보낸 사람, outbox일 받는 사람의 사용자 정보를 가져오도록 변경
.

[fix] 보낸 쪽지함에서 받는 사람 닉네임을 표시

---

src/components/common/ApplyPositionButton.tsx
src/components/projectDetail/ApplyModal/ApplyModal.tsx
src/components/projectDetail/ApplyModal/ApplyPositionArea.tsx
src/components/projectDetail/MemberInfoArea.tsx
src/components/projectDetail/ProjectInfoArea.tsx
src/components/projectDetail/mobile/MobileApplyButtonArea.tsx
src/components/projectDetail/mobile/MobileMemberInfoArea.tsx
src/components/projectDetail/mobile/MobileWirterToProjectInfoArea.tsx
src/components/projectDetail/mobile/projectDetailMobile.tsx
src/pages/ProjectDetailPage.tsx
src/utils/positions.ts

프로젝트 상세보기 페이지의 유저 피드백을 반영하였습니다.
Closes #351 #357 #363 
- 모바일 버전 마감완료 후 지원자 목록 숨기기
- 프로젝트 정보에서 모집 인원이 0명인 포지션 숨기기(데스크탑/모바일)
- 참여 중인 인원이 없을 경우 `아직 모집중이에요 :/` 문구 추가(데스크탑/모바일)
- 필요 스택 숨길 경우 높이 조절 (모바일)
- 모집 인원이 0명인 포지션은 지원하기 모달에서 클릭되지 않도록 처리(데스크탑/모바일)
- 아직 팀원이 모집되지 않은 포지션의 경우 숨김 처리(데스크탑/모바일)

[PR] 프로젝트 상세보기 페이지 유저 피드백 반영#1

---

src/apis/boardService.ts
src/components/ContentCard.tsx
src/components/MobileContentCard.tsx
src/components/findproject/FindProjectList.tsx
src/components/findproject/mobile/FindProjectMobileList.tsx
src/hooks/useFindProject.ts
src/pages/FindProjectPage.tsx

close #369 
카드에서 좋아요 클릭시 카운트 바로 반영 되도록 수정
- firebase 좋아요 카운트 가져오는 로직 생성
- PC & Mobile Content Card에 좋아요 기능 클릭시 카운트 되도록 로직 수정

[feat] 팀원 찾기 페이지 카드 좋아요 클릭시 카운트 바로 반영 되도록 변경

---

src/components/mypage/TextInput.tsx
src/components/mypage/mobile/MobileTopTab.tsx
src/components/mypage/mobile/MobileUserInfo.tsx
src/hooks/useUpdateProfile.ts

Fixes #368 
마이페이지, 회원가입에서 사용되는 인풋 태그 클리어 버튼 버그,
모바일 마이페이지 정보수정 이메일 부분의 placeholder가 클리어 버튼과 겹치는 현상 수정을 했습니다.
* TextInput 컴포넌트의 input 태그 `defaultValue` 속성을 `value`로 수정
* 모바일 마이페이지 정보수정 이메일 placeholder 수정
* 모바일 탭 컴포넌트명 오타 수정
.

[fix] 인풋태그 클리어 버튼 버그, placeholder 수정

---

src/components/main/Calendar/ProjectList.tsx

메인 페이지에서 프로젝트 캘린더의 날짜를 변경하면, 프로젝트 리스트 슬라이더를 첫번째 페이지로 이동하는 기능을 추가했습니다.
react slick 라이브러리의 [slickGoTo method](https://react-slick.neostack.com/docs/api/#slickGoTo)를 사용했습니다.
- ProjectList 컴포넌트에서 DayList가 변경되면 slickGoTo(0) 메소드를 실행
.

[feat] 날짜를 변경하면 프로젝트 리스트 슬라이더를 첫번째 페이지로 이동

---

src/components/TextEditor.tsx

베타 테스터 피드백 중 Toast UI Editor 툴바 아이템이 렌더링 되지 않는 에러를 수정했습니다.
- toolbarItems 배열을 컴포넌트 외부로 위치 이동
.

[fix] 에디터 툴바 렌더링이 안되는 에러 수정

---

src/components/main/banner/MainBanner.tsx
src/hooks/useDetailProject.ts
src/hooks/usePublicProfile.ts

기존: useQuery를 이용하는 페이지에 접근 시 두번째부터는 캐싱 데이터로 인해 로딩 페이지가 나타나지 않음
변경: useQuery 옵션에 suspense를 적용하여 fetching 시에도 로딩 페이지가 나타나도록 변경함
- useDetailProject, usePublicProfile 훅의 query 옵션에 suspense를 추가
.

[feat] 프로젝트 상세보기, 공개프로필 페이지의 query에  suspense 적용

---

src/hooks/useEditBoard.ts
src/hooks/useNote.ts
src/hooks/useUpdateProfile.ts
src/hooks/useWrite.ts

공백 문자열을 입력할 때 유효성 검사가 통과되는 버그가 있어
텍스트를 trim 후 유효성 검사를 진행하도록 수정했습니다.
- 프로젝트 글 작성/수정 - 제목, 내용
- 쪽지 - 제목, 내용
- 회원가입 - 닉네임, 연락처
.

[fix] 유효성 검사 전 텍스트 trim

---

src/components/common/myProjectList/ProjectsTab.tsx
src/components/mypage/mobile/MobileProjectList.tsx
src/components/projectDetail/ApplyModal/ApplyModal.tsx
src/components/projectDetail/ApplyModal/ApplyModalButtonArea.tsx
src/components/projectDetail/ApplyModal/ApplyMotiveArea.tsx
src/components/projectDetail/mobile/MobileModal/MobileApplyModal.tsx
src/components/projectDetail/mobile/projectDetailMobile.tsx
src/hooks/useApply.ts
src/pages/ProjectDetailPage.tsx

Close #416 
Close #417 
- 지원하기 제출 시 수정 및 확인이 안됨을 고지하기 위하여 Alert -> Confirm Alert로 수정
- 지원하기 커스텀 훅 `useApply` 추가
- 모바일 지원하기 컴포넌트 분리
- 공개프로필 탭버튼 디자인 수정

[PR] 지원하기 모달 제출 시 수정 안됨 고지, 공개프로필 탭버튼 디자인 수정

---

src/apis/boardService.ts
src/apis/postDetail.ts
src/components/common/myProjectList/ProjectItemMembers.tsx
src/components/editpage/EditPageDeadline.tsx
src/components/login/SetProfile.tsx
src/components/projectDetail/ApplicantCard.tsx
src/components/projectDetail/ApplicantListArea.tsx
src/components/projectDetail/InviteModals/InviteModal.tsx
src/components/projectDetail/MemberInfoArea.tsx
src/components/projectDetail/ParticipantsProfile.tsx
src/components/projectDetail/mobile/MobileApplicantCard.tsx
src/components/projectDetail/mobile/MobileMemberInfoArea.tsx
src/components/projectDetail/mobile/MobileModal/MobileInviteModal.tsx
src/hooks/useApply.ts
src/hooks/useDetailProject.ts
src/hooks/useFindProject.ts
src/hooks/usePublicProfile.ts

Closes #428 
프로필 변경 시 공개프로필의 프로젝트 목록과 상세페이지의 초대하기 모달, 지원자 목록, 참여자 목록에 반영이 안됐던 문제를 해결하였습니다.
- 상페페이지 지원자 목록 프로필 uid로 조회
- 상세페이지 참여자 목록 프로필 uid로 조회
- 초대하기 모달 지원자 프로필 uid로 조회
- 공개프로필의 참여자 목록 프로필 uid로 조회

[PR] 프로필 변경 시 프로젝트 상세보기 페이지, 초대하기 모달, 공개프로필에 반영

---

src/apis/boardService.ts
src/components/ContentCard.tsx
src/components/MobileContentCard.tsx
src/hooks/useFindProject.ts

무한 스크롤 로직 tanstack react query 로직으로 변경
콘텐츠 카드 좋아요 위치 변경 및 클릭시 디테일로 가는 버그 수정
- 무한 스크롤 로직 useInfiniteQuery 를 통해서 가져오도록 수정
- 콘텐츠 카드 좋아요 아이콘 위치 조정
- 콘텐츠 카드 좋아요 클릭시 디테일로 가능 부분 수정

[fix] 무한 스크롤 로직 변경 및 콘텐츠 카드 하트 수정

---

src/apis/postDetail.ts
src/components/projectDetail/Likes.tsx
src/components/projectDetail/WriterToShareArea.tsx
src/components/projectDetail/mobile/MobileWirterToProjectInfoArea.tsx

Closes #438 #439 
상세보기 새로고침 시 하트 유지,
작성자 공개프로필 링크 이동 이벤트 영역을 수정했습니다.
* 새로고침 시 하트 유지되도록 useEffect문 추가
* 메인,프로젝트 찾기 페이지에서 초기에 countLike가 undefined일 때의 에러 예외처리
* 모바일 상세보기 -> 작성자 공개 프로필 이동 영역 수정 (해당 div 어디든 -> 사진 닉네임 영역)
* 데스크탑 상세보기 -> 작성자 공개 프로필 이동 영역 수정 (프로필 사진 -> 사진,닉네임 영역) 
.

[fix] 상세보기 새로고침 시 하트, 작성자 공개프로필 링크 이동 이벤트 영역 수정

---

src/components/projectDetail/Likes.tsx
src/components/projectDetail/mobile/MobileModal/MobileInviteModal.tsx
src/hooks/useFindProject.ts

Closed #441 #442 
PC 콘텐츠 카드 관심수 카운트 제대로 적용 안되는 버그 수정
Mobile 특정 디테일 게시판 displayName 에러 수정
- 팀원찾기 페이지 useInfiniteQuery 의 querykey invalid 처리
- 디테일 페이지 InviteModal displayName optional chaining 적용

[fix] 콘텐츠 카드와 특정 디테일 게시판 버그 수정

---

src/components/common/ValidationToastPopup.tsx
src/hooks/useEditBoard.ts

- 토스트 팝업 메시지 모바일 사이즈 추가
- console.log 이력 삭제
- Toast Message Popup isMobile 사이즈 추가
- useEditBoard 에 imgRef console.log 삭제

[fix] 토스트 팝업 모바일 사이즈 추가 및 콘솔 삭제

---

src/components/common/ValidationToastPopup.tsx

- 토스트 메시지 팝업창 400px 미만에서 글자크기 깨지는 부분 수정
- PC 버전 display: 'none' 으로 인한 CSS버그 수정
- isMobile 일때 텍스트 사이즈 조정
- PC일때 display: 'none' -> '' 로 수정

[fix] Toast Message Popup 모바일 CSS 수정
